### ISSUE TITLE
upload-symbol-maps is unclear and appears to be a dead option?

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cli#1009]
https://github.com/getsentry/sentry-cli/blob/0af08560161b7a2eccdd613ba847ea8667a36e74/src/commands/upload_dif.rs#L169

It appears this option is not referenced anywhere.  It's also very unclear what it's expected result should be and how it interplays with `symbol-maps`.

**Comment by kamilogorek** [comment]
You are correct, it looks like that. Providing `bcsymbolmap` as a value to `type` option should have the desired effect. cc @flub

**Comment by flub** [comment]
with `--symbol-maps` you need to download the dSYM files from App Store Connect to your local machine after a bitcode upload and then sentry-cli will use the `dsymutil` tool on your local machine to first merge the BCSymbolMap data into the dSYM files before uploading the modified dSYMs.

In any case, (if not filtered) sentry-cli will upload the BCSymbolMap files as well as the OriginalUUIDMapping plist files directly, which does not require you to download the dSYMs from App Store Connect before you can call sentry-cli, this can be easier for CI machines to manage the build.  The flipside of this is that you need to use the [App Store Connect integration](https://docs.sentry.io/platforms/apple/dsym/#bitcode-appstore) on sentry so that sentry can download the dSYM files directly from App Store Connect and merge the BCSymbolMaps on the server side.

The, err, intention of the flag was that if present and the server sentry-cli talks to (e.g. when talking to a self-hosted sentry server) does not yet support uploading of BCSymbolMaps then it would error out if there were actual BCSymbolMaps to upload.  It seems that this was somehow missed though.

**Comment by kamilogorek** [comment]
Should we just hide/remove the flag, or do you want to add this feature in the future?

**Comment by flub** [comment]
I think we need to be a little careful with removing it since the sentry-fastlane-plugin already supports this flag as well.  But realistically maybe removing it is the best option until someone is unhappy about that situation.

**Comment by kamilogorek** [comment]
Ugh right, it'd fail if we remove this option. Let leave it for now then and hopefully we can get it useful one day.

**Comment by lhunath** [comment]
If `upload-symbol-maps` remains or returns to the `--help` output; I recommend making the distinction between it and `--symbol-maps` more clear, such as by stipulating that `--symbol-maps` works locally, while `--upload-symbol-maps` works remotely.

**Comment by lhunath** [comment]
One option might be to make `--upload-symbol-maps` behave like `--symbol-maps` does today, and to make `--symbol-maps` operate exclusively locally in its absence.
