### ISSUE TITLE
Internalize emission of warnings/errors

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cli#1092]
Instead of having developers consume the status code from running the executable to upload symbols in an Xcode _Run Script_ Build Phase and then printing a warning if it failed (as described [here](https://docs.sentry.io/platforms/apple/dsym/?_ga=2.128113675.689385093.1640731068-498091088.1640731068#uploading-symbols-with-sentry-cli)), the warning could itself be printed from within the executable. The same format would work; anything printed to stdout that starts with `warning: ` would get picked up by Xcode and presented in the Issue Navigator (and likewise for `error: `, in the case that we make the change suggested in https://github.com/getsentry/sentry-cli/issues/1091).

**Comment by armcknight** [comment]
@getsentry/team-mobile

**Comment by kamilogorek** [comment]
@armcknight this, unfortunately, won't be that trivial to change, if any. The problem with this is that we are demonizing the upload process, so it won't block and can happen in the background.

Because of that, all communication with users is done via notifications, not logging. stdout/err are redirected to a temp file and then if something goes wrong, we show an appropriate applet that can then print the whole output when the user decides to do so via button press.

see: https://github.com/getsentry/sentry-cli/blob/02f15e9b19139754aa62ee3f4a62974b3c24c990/src/utils/xcode.rs#L343-L352
see: https://github.com/getsentry/sentry-cli/blob/02f15e9b19139754aa62ee3f4a62974b3c24c990/src/utils/xcode.rs#L378-L384

Tbh I think that code below is kinda redundant, however, it's still required in case the cli itself breaks somehow, not the upload process itself.

```
if [ ! $? -eq 0 ]; then
echo "warning: sentry-cli - $ERROR"
fi
```

**Comment by armcknight** [comment]
I see where you're coming from. This touches on a bigger issue though, alluded to in the linked issue (https://github.com/getsentry/sentry-cli/issues/1091)... if `sentry-cli` fails after the Xcode build finishes, the Xcode build itself will appear to have succeeded, even though in actuality an important part failed. This is especially my worry thinking about deploys running without supervision on CI boxes. Has this historically been an issue with customers? I'm happy to open a separate issue about that: `sentry-cli` should always break Xcode builds on issues that can lead to broken app deploys.

**Comment by kamilogorek** [comment]
> Has this historically been an issue with customers?

No, not that I know of to be honest.

> if sentry-cli fails after the Xcode build finishes, the Xcode build itself will appear to have succeeded, even though in actuality an important part failed. (...) This is especially my worry thinking about deploys running without supervision on CI boxes. (...) sentry-cli should always break Xcode builds on issues that can lead to broken app deploys.

That's already possible when uploading artifacts with `--force-foreground` flag. It won't demonize the process, keeping it in the main thread, thus failing the whole build if it doesn't succeed.
