### ISSUE TITLE
Organization not found error message

### ISSUE THREAD

**Issue by matdube** [getsentry/sentry-cli#1128]
I got a _project not found_ error while creating a release. I made sure the project slug was correct, but it turns out my organization had a typo in it. I believe it would be very useful to have distinct errors for project not found and org not found.

**Current behavior**
```
~$ sentry-cli release --org 'correct-org' --project 'wrong-project' new 'my-release'
error: project not found
~$ sentry-cli release --org 'wrong-org' --project 'correct-project' new 'my-release'
error: project not found
```

**Suggested behavior**
```
~$ sentry-cli release --org 'correct-org' --project 'wrong-project' new 'my-release'
error: project not found
~$ sentry-cli release --org 'wrong-org' --project 'correct-project' new 'my-release'
error: organization not found
```

**Comment by kamilogorek** [comment]
The `/projects/<org>/<project>/releases` endpoint that we use for the command above, is using a complex filter that's bound to both, project and organization. We have to do that due to the security and privacy nature of our SaaS product.

You can use `sentry-cli projects --org foo list` (or skip `--org` if configured via config file) instead to make sure that your organization slug and permissions are valid.
