### ISSUE TITLE
XML Parsing Error on AndroidManifest.xml

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-cli#116]
Originally reported against sentry main (https://github.com/getsentry/sentry/issues/6031#issuecomment-327018913)

I'm building app on Jenkins CLI, and I'm facing error (log):
```
sentry-cli update to 1.19.1 is available!
run sentry-cli update to update
error: Malformed XML: Unexpected token: /> (247:48)
 FAILED
```

This happens for Sentry 1.4.0-1.5.2 SDK (+ Android plugin).  Locally app is building just fine but not on Jenkins where it tries to update via Sentry-cli (not used). Downgrading doesn't solve issue (even that I build with those versions earlier on).
Gradle is build with :

```
autoProguardConfig false
    autoUpload false
```

**Comment by mitsuhiko** [comment]
@tajchert can you share the AndroidManifest.xml with me? I'm not sure how it happens but apparently something there is malformed XML.

**Comment by tajchert** [comment]
Hi,
I will rather avoid publishing Manifest (sorry this is not under my decision).
Probably important might be the fact we are using AndroidAnnotations (some generated classes in Manifest with "_") - version 4.0.0.
I will try to revert some changes till it correctly builds - I'm on 2 days vacations so it might take some time (if somebody is experiencing same issue - go ahead).

**Comment by bretthoerner** [comment]
Any chance you could just post the snippet around `(247:48)`, or send it to us privately? This is the only report like this that I know of, so we will have a hard time debugging without it.

**Comment by tajchert** [comment]
Yeah, I'm fully aware of Manifest being published and need of it to solve issue but this is a company decision to post it here and not mine (no matter how I would like to do so).

48 line:
```
<receiver android:name=".XYZ_">
            <intent-filter>
                <action android:name="XYZ" />
                <action android:name="XYZ" />//48 line
                <action android:name="XYZ" />
                <action android:name="XYZ" />
            </intent-filter>
        </receiver>
```

```
<meta-data
            android:name="XYZ"
            android:value="XYZ" />//247 line
```

Neither of those lines was changed during since last release.
I will try to compile tomorrow with some reverted changes in Manifest - sorry I'm on a vacations.

**Comment by tajchert** [comment]
Hi,
This issue is solved - our mistake. 

We had issue with:
```
            android:screenOrientation="portrait" /> 
            android:screenOrientation="portrait"/> 
```

Which somehow compiled and didn't even highlight in Android Studio (even went though Jenkins build). But once Sentry Android plugin was active it failed to build with mentioned error - however line number was after processing (/build/ path) and not initial - proper one.

Sorry for fuss.

**Comment by bretthoerner** [comment]
@tajchert Thanks for updating us on this!

**Comment by TippuFisal** [comment]
Hi Guys,
Make sure there is no duplication of any line of code in XML or manifest etc... 

**Example :**
<activity
            android:name=".kotlin.ui.example.activity.ExampleActivityKt"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            **android:theme="@style/AppTheme.NoActionBar"/>
            android:theme="@style/AppTheme.NoActionBar"/>  // Code duplication**
