### ISSUE TITLE
sentry-cli bash-hook fails if using perl and any error happens

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry-cli#1260]
CC @mitsuhiko 

```
$ cat foo.sh
sentry-cli bash-hook > foo.txt
eval "$(sentry-cli bash-hook)"
exit 2

$ ./foo.sh
./foo.sh: eval: line 63: syntax error near unexpected token `>'
```

That's probably this line:
> 1> >(tee >(perl '-MPOSIX' -ne '$|++; print strftime("%Y-%m-%d %H:%M:%S %z: ", localtime()), "stdout: ", $_;' >> "$_SENTRY_LOG_FILE")) \

**Comment by mitsuhiko** [comment]
@armenzg do you have an idea which shell is executing this for you?

**Comment by armenzg** [comment]
`$SHELL` says `/bin/zsh`

```
cat foo.sh
sentry-cli bash-hook > foo.txt
echo $SHELL
eval "$(sentry-cli bash-hook)"
```

**Comment by szokeasaurusrex** [comment]
@armenzg Per the [docs](https://docs.sentry.io/product/cli/send-event/#bash-hook), and per the name of the command being `bash-hook`, the `bash-hook` only supports being run in the `bash` shell. Using `zsh` is unsupported. 

Fixing your problem is as simple as using `bash` to run the `foo.sh` script, like so:
```
$ bash foo.sh
```

See also https://github.com/getsentry/sentry-cli/issues/1848.
