### ISSUE TITLE
upload-dif --no-upload should display what files would be uploaded

### ISSUE THREAD

**Issue by benpeck-eepics** [getsentry/sentry-cli#1279]
Using sentry-cli 2.3.1 release on Windows 10

When using the --no-upload flag to upload-dif, the cli immediately returns and says skipping upload.

It would be much more useful if the cli went ahead and listed which files it detected in the path I supplied, analyzed them, and listed which are considered new files before deciding not to upload any of them.

Thanks!

**Comment by kamilogorek** [comment]
Thanks for the feedback. It sounds reasonable, however, it's more work than just printing this data right now.

The things that will end up being uploaded, are dependent on the receiving server's capabilities. Each server can change its handled formats and disable/enable specific features. Thus for us to know what will effectively be uploaded, we need to do some processing and "server talk" beforehand.

I will leave this issue open so we can have a reference to it once there is some spare time for such improvements. Thanks!

**Comment by benpeck-eepics** [comment]
Ok thanks for the response. As added motivation, the[ current documentation](https://docs.sentry.io/product/cli/dif/) really makes it sound like this flag behaves in the why I describe in the original post (bold is my emphasis):

> --no-upload
Disables the actual upload. **This runs all steps for the processing** but does not trigger the upload (this also automatically disables reprocessing). This is useful if you just want to verify the setup or skip the upload in tests.

**Comment by gregcotten** [comment]
Came here to create an issue to this effect. 

This would be really useful. In environments where we want to verify that *some* debug symbols might be uploaded if we're releasing, it's really useful to log this information.

**Comment by szokeasaurusrex** [comment]
@benpeck-eepics, @gregcotten could you please explain your concrete use case for outputting the would-be-uploaded debug files when running `--no-upload`?

There seems to be low demand for this feature, so I would like to understand what you are trying to accomplish to see whether there would be any alternative solutions that would require less development effort.

**Comment by gregcotten** [comment]
> @benpeck-eepics, @gregcotten could you please explain your concrete use case for outputting the would-be-uploaded debug files when running `--no-upload`?
> 
> There seems to be low demand for this feature, so I would like to understand what you are trying to accomplish to see whether there would be any alternative solutions that would require less development effort.

It's useful in a CI sense to make sure debug symbols can be found at all. My issue was that I updated my Swift toolchain and suddenly my release GitHub Action was no longer uploading debug symbols. Turns out I needed to adjust build flags to compensate. I thought it would be useful to have a way of verifying *some number* of debug symbols etc would actually get uploaded as part of our CI, and having sentry-cli do it would be super convenient because at the end of the day, I am using sentry-cli to find the debug symbol files for me and upload them.

I can definitely get away with searching for .pdb and .dSYM files myself as a sanity check so if this really takes significant resources to add as a feature I would say "don't do it"

**Comment by szokeasaurusrex** [comment]
Ah okay, I understand @gregcotten. I think what might actually be a better solution for your use case is a `--strict` flag that causes the upload command to fail with non-zero exit status code when we don't find any files to upload. This option already exists for uploading sourcemaps, so we would just be porting this feature over to also work with debug file uploads.

Due to technical debt in the codebase, adding the `--strict` flag would be a non-trivial change, but it would likely be easier than reworking the `--no-upload` option to also print the would-be-uploaded files. I am honestly considering deprecating `--no-upload`, since I don't think it is that helpful right now, and we can probably find better ways to address the use cases that folks would be using `--no-upload` for.

Would having the `--strict` flag, as I've described it here, solve your use case? If yes, I will create a separate issue for this feature, and I will close this issue.

**Comment by gregcotten** [comment]
> Ah okay, I understand [@gregcotten](https://github.com/gregcotten). I think what might actually be a better solution for your use case is a `--strict` flag that causes the upload command to fail with non-zero exit status code when we don't find any files to upload. This option already exists for uploading sourcemaps, so we would just be porting this feature over to also work with debug file uploads.
> 
> Due to technical debt in the codebase, adding the `--strict` flag would be a non-trivial change, but it would likely be easier than reworking the `--no-upload` option to also print the would-be-uploaded files. I am honestly considering deprecating `--no-upload`, since I don't think it is that helpful right now, and we can probably find better ways to address the use cases that folks would be using `--no-upload` for.
> 
> Would having the `--strict` flag, as I've described it here, solve your use case? If yes, I will create a separate issue for this feature, and I will close this issue.

Eh I guess I will just do some sort of smoke test to make sure there are debug files present. 

I agree "--no-upload" doesn't really seem to be useful (you might as well just not call the cli tool at all?)

**Comment by szokeasaurusrex** [comment]
> I agree "--no-upload" doesn't really seem to be useful (you might as well just not call the cli tool at all?)

It seems like `--no-upload` was added a really long time ago (well before I took over maintaining this codebase), so I am lacking context on why it was added. But, from looking at the code, I am struggling to see how it is useful/what it is meant to do. We also don't have an equivalent `--no-upload` option for our `sourcemaps upload` command (which I believe was added after `debug-files upload`/`upload-dif`, so I think we will just deprecate `--no-upload` for now.
