### ISSUE TITLE
support for s390x

### ISSUE THREAD

**Issue by tseeling** [getsentry/sentry-cli#1312]
It would be very nice to have an installable file for s390x.
I try to compile element-web (a matrix client) and it fails because the docker build process cannot download sentry-cli.
I'd be willing to do the actual compile on that architecture and provide the file if someone can guide me what to do (I'm running Redhat 7.8 and 8.6 on s390x).

**Comment by kamilogorek** [comment]
There are no plans for implementing this,, however any PRs are welcome :)

**Comment by szokeasaurusrex** [comment]
Hi @tseeling, we are not planning to add support for s390x, as @kamilogorek mentioned previously, so I am going to close this issue.

You should be able to compile Sentry CLI from source for s390x, since [Rust should support](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools) this architecture. You can reach out if you have any problems, but keep in mind that we do not officially support s390x, so our ability to help in case of a problem specific to that architecture will be quite limited (especially because I don't think we would have easy access to such a system)
