### ISSUE TITLE
Xcode cannot find sentry-cli when installed through Brew, but works with manual install

### ISSUE THREAD

**Issue by brianp-tommycarwash** [getsentry/sentry-cli#1320]
### Environment

MacBook Pro (14-inch, 2021), Apple M1 Max
Xcode Version 13.4.1 (13F100)
Sentry-cli 2.5.2

### Steps to Reproduce

1. Install via Brew and setup project as instructed by documentation.
2. Setup a build phase run script in Xcode, add the following;
```
if which sentry-cli >/dev/null; then
export SENTRY_ORG=your-org-here
export SENTRY_PROJECT=your-project-here
export SENTRY_AUTH_TOKEN=[TOKEN]
ERROR=$(sentry-cli upload-dif "$DWARF_DSYM_FOLDER_PATH" 2>&1 >/dev/null)
if [ ! $? -eq 0 ]; then
echo "error: sentry-cli - $ERROR"
fi
else
echo "error: sentry-cli not installed, download from https://github.com/getsentry/sentry-cli/releases"
fi
```
3. build the project.

### Expected Result

Build Success

### Actual Result

Build Failed, sentry-cli: command not found

### Alternative Install

When I uninstalled from brew and installed the manual way, `curl -sL https://sentry.io/get-cli/ | bash`, then I get a build success.

**Comment by kamilogorek** [comment]
This means that your homebrew binaries are not discoverable for XCode, due to either incorrect `$PATH` configuration of your system, or that env var being overwritten in your XCode.

In case former is true - https://sourabhbajaj.com/mac-setup/Homebrew/
In case latter is true - https://exchangetuts.com/where-is-path-set-in-xcode-1639725016802360
