### ISSUE TITLE
npm cli install without postinstall

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry-cli#1360]
`postinstall` creates a whole host of issues which it would be nice to not have to deal with.

I've seen a similar issues when distributing native node binaries and wonder whether some of the solutions I've seen in use there might be an improvement here.

Firstly, you publish an npm package per platform/arch combo (`@sentry/cli-{platform}-{arch}`) and include the cli binary in there. 
- In `package.json` set `main` as the path to the binary and then it can be found later by simply `require.resolve('@sentry/cli-${process.platform}-${process.arch}')` 
- In `package.json` correctly define `os` and `cpu` properties which ensures that they will only install on the correct platform/arch
- You can even set `bin` in these packages if you want them to be directly accessible.

Then in `@sentry/cli` you list all the above as `optionalDependencies`. After this, when installing `@sentry/cli`, npm/yarn will attempt to install all the optional dependencies and only succeed on those where the `os` and `cpu` match. 

Bonus: If your JavaScript code used to find the binary uses complicated enough dynamic paths construction, `@vercel/nft` gives up and wont include them.

This approach is already used by [Parcel](https://www.npmjs.com/package/@parcel/css-darwin-arm64), [Next.js](https://www.npmjs.com/package/@next/swc-darwin-arm64) and [plenty of others](https://www.npmjs.com/search?q=darwin-arm64).

### Downsides?
- It is perhaps abusing `optionalDependencies` but everyone appears to be on this train now so maybe it wont crash?
- Does npm/yarn have to download all the optional dependencies before checking the `os` and `cpu`? 🤔

**Comment by kamilogorek** [comment]
ref: https://github.com/npm/rfcs/blob/528fa298a3529dcae3f58cbf2f9a577ba16b479f/accepted/0000-package-distributions.md

**Comment by me4502** [comment]
Given the size of the sentry-cli binary, in poor network conditions this can be a substantial issue on CI. Currently this breaks the Yarn caching & install model (https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall), leading to the cache being bypassed and the entire binary being downloaded on every run.

Would definitely be good to not have postinstall used to download a large binary

**Comment by krystofwoldrich** [comment]
- linking related issue https://github.com/getsentry/sentry-react-native/issues/2688

**Comment by lforst** [comment]
Plan of action:
- [ ] Create packages for all different architectures (just the package.json) @lforst 
- [ ] Configure Rust build tooling to emit the binaries into the packages in the right place @szokeasaurusrex 
- [ ] Configure craft to publish the packages @lforst 
- [ ] Add the architecture packages as optional dependencies (we will likely need some sort of prepublish script that always aligns the dependency versions) @lforst 
- [ ] Point the JS entry point to the new architecture binaries @lforst 
- [ ] Turn the post-install script to a no-op and add a deprecation notice because we will want to remove it in the next major. @lforst
