### ISSUE TITLE
sentry-cli is requiring pre-release Xcode 14.1

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-cli#1366]
### Environment

```
hubstaff@Ganymede ios 1$ xcode-select -p
/Applications/Xcode-14.0.1.app/Contents/Developer
```

### Steps to Reproduce

1. `brew tap getsentry/tools && brew install getsentry/tools/sentry-cli`

### Expected Result

`sentry-cli` is installed.

### Actual Result

```
==> Installing sentry-cli from getsentry/tools
Error: Your Xcode (14.0.1 => /Applications/Xcode-14.0.1.app/Contents/Developer) is too outdated.
Please update to Xcode 14.1 (or delete it).
Xcode can be updated from the App Store.

Error: Your Command Line Tools (CLT) does not support macOS 13.
It is either outdated or was modified.
Please update your Command Line Tools (CLT) or delete it if no updates are available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.1.
```

Through some mechanism, `sentry-cli` is requiring the installation of both Xcode 14.1 and the Command Line Tools for Xcode 14.1. This is excessive, since Xcode 14.1 is pre-release software and many people will not have updated yet, nor SHOULD they, just to use `sentry-cli`.

This full on breaks our CI since a part of the process is that we run a `Brewfile` and the CI machine does not have Xcode 14.1 set up.

Unsure how this snuck in (or where exactly to report).

**Comment by kamilogorek** [comment]
This is not caused by the CLI. Our formulae does not perform any checks - https://github.com/getsentry/homebrew-tools/blob/master/Formula/sentry-cli.rb

This is caused by the recent brew release bumping minimal xcode requirement to `14.1` for macOS 13 and your CI is probably not pinned to any specific brew version, thus it uses latest, which requires that newer xcode version.

ref: https://github.com/Homebrew/brew/pull/13980
ref: https://github.com/Homebrew/brew/releases/tag/3.6.5
