### ISSUE TITLE
MacOS: Error: spawn /node_modules/@sentry/cli/sentry-cli ENOENT

### ISSUE THREAD

**Issue by atokuswanto** [getsentry/sentry-cli#1393]
### Environment

MacOS Ventura 13.0
sentry-cli 1.74.6

### Steps to Reproduce

1. sudo npm install -g @sentry/cli@1.74.6 
2. sentry-cli --help

### Expected Result

It should show sentry-cli help texts.

### Actual Result

```
Error: spawn /Users/apple/.nvm/versions/node/v14.18.3/lib/node_modules/@sentry/cli/sentry-cli ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /Users/apple/.nvm/versions/node/v14.18.3/lib/node_modules/@sentry/cli/sentry-cli',
  path: '/Users/apple/.nvm/versions/node/v14.18.3/lib/node_modules/@sentry/cli/sentry-cli',
  spawnargs: [ '--help' ]
}
```

### Further Info

I noticed that sentry-cli executable was installed in @sentry/cli/bin directory. So I've move executable up to  @sentry/cli directly, and updated code part to require .js directory.
And, I executed sentry-cli --help.
Actual result, it does nothing, just stuck on it.

**Comment by kamilogorek** [comment]
> I noticed that sentry-cli executable was installed in @sentry/cli/bin directory.

This is a correct path, as this is just a runner https://github.com/getsentry/sentry-cli/blob/master/bin/sentry-cli that our `package.json` points to.

What happened most likely is that due to installing with `sudo`, npm decided to skip `post-install` script, which fetches an actual rust-compiled binary.

See: https://github.com/getsentry/sentry-cli#node

> When installing globally, make sure to have set [correct permissions on the global node_modules directory](https://docs.npmjs.com/getting-started/fixing-npm-permissions). If this is not possible in your environment or still produces an EACCESS error, install as root:

I'd try to run `sudo npm install -g @sentry/cli --unsafe-perm` first, and if that still persist, go to `/Users/super/.nvm/versions/node/v14.18.3/lib/node_modules/@sentry/cli` and run `node scripts/install.js` directly and see what it tells you.

**Comment by atokuswanto** [comment]
Hi @kamilogorek 
1. I've tried `sudo npm install -g @sentry/cli --unsafe-perm`, issue still persists.
2. I've tried `/Users/apple/.nvm/versions/node/v14.18.3/lib/node_modules/@sentry/cli` and run `node scripts/install.js` directly, issue has gone.
Thank you.

**Comment by kamilogorek** [comment]
This means that the use of `sudo` (probably together with how `nvm` is installed in your env) prevented the script to install the binary in its place.
When you run it manually, you do it with a different set of permissions, which made it work.
Unfortunately, this is an env setup-specific issue, so there's not much we can do other than point users in the right direction.
Let me know in case you have more questions. Cheers!
