### ISSUE TITLE
Provide builds for ppc64le

### ISSUE THREAD

**Issue by bkeys** [getsentry/sentry-cli#1418]
### Problem Statement

I am trying to host an element chat server on my ppc64le server, and I get the following error:
```
Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.74.6/sentry-cli-Linux-ppc64.
```
I don't think it should be a problem, but I am not too familiar with the ins and outs of your platform.

### Solution Brainstorm

It would be nice if ppc64le architecture was added to your official releases; I'd be willing to help anyway I can to see it happen.

**Comment by M-Stenzel** [comment]
Well, **bkeys** is not the only one.... :)

I want to use the Parula app [](https://parula.beonex.com) on ppc64le, and this depends on sentry-cli as well.
Building the sentry-cli binary from source (latest version) works out of the box, but the helper script is not very helpful, since it
prevents running the binary easily (it checks for unsupported platforms). So maybe you can adjust so that running sentry-cli on ppc64le is not a hassle.

Regards, Martin.

I had to use a VERY dirty hack, replace the script with the binary and make that immutable...
