### ISSUE TITLE
Unable to download sentry-cli binary

### ISSUE THREAD

**Issue by kle-pra** [getsentry/sentry-cli#1451]
### Environment

Ubuntu 20.04
```
❯ node -v
v18.12.1
❯ npm -v
8.19.2
```

### Steps to Reproduce
I try to install latest version with:

`npm i @sentry/cli`

### Expected Result

Should install library with success. I works with version 2.11: `npm i @sentry/cli@2.11.0`

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?
```
❯ npm i @sentry/cli
npm ERR! code 1
npm ERR! path /home/user1/projects/project/frontend/node_modules/@sentry/cli
npm ERR! command failed
npm ERR! command sh -c -- node ./scripts/install.js
npm ERR! [sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/2.12.0/sentry-cli-Linux-x86_64
npm ERR! Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/2.12.0/sentry-cli-Linux-x86_64.
npm ERR! Error message: request to https://downloads.sentry-cdn.com/sentry-cli/2.12.0/sentry-cli-Linux-x86_64 failed, reason: connect EHOSTUNREACH 2a04:4e42:400::729:443
npm ERR! Error code: EHOSTUNREACH

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user1/.npm/_logs/2023-02-01T11_16_45_673Z-debug-0.log
```

**Comment by kamilogorek** [comment]
This is a problem with your local network or some npm configuration. Be it either dns resolving, firewall or office setup.
The issue here is that your network is unable to connect to or `https://downloads.sentry-cdn.com` CDN.

You can use github as an alternative for fetching binaries: `https://github.com/getsentry/sentry-cli/releases/download/`
How to do that exactly, can be found here: https://github.com/getsentry/sentry-cli#node

Cheers!

**Comment by kle-pra** [comment]
Tnx, for anyone interested, it was problem with my **IPv6** setting (wrong fixed value for DHCP) for the **network**. 

Direct link in browser (https://downloads.sentry-cdn.com/sentry-cli/2.12.0/sentry-cli-Linux-x86_64) worked even before.
