### ISSUE TITLE
error: Failed to load .sentryclirc file from the home folder.

### ISSUE THREAD

**Issue by arielelkin** [getsentry/sentry-cli#1864]
### Environment

```
$ sentry-cli --version
sentry-cli 2.23.0
```

### Steps to Reproduce

```
$ sentry-cli upload-dif \
            --auth-token token \
            --org orgname \
            --log-level debug \
            --project projectname \
            symbols
error: Failed to load .sentryclirc file from the home folder.
  caused by: Permission denied (os error 13)
thread 'unnamed' panicked at 'Config not bound yet': src/config.rs:85

   0: backtrace::backtrace::trace

zsh: abort      sentry-cli upload-dif --auth-token  --org shapedbyiris 
```

**Comment by szokeasaurusrex** [comment]
Hey @arielelkin, thank you for reporting this issue. We will look into it is soon as we can.

**Comment by szokeasaurusrex** [comment]
Hi @arielelkin, I attempted to reproduce your issue; however, the command you provided succeeds in most cases. The only case where I encountered the same error that you did was when the user running the CLI lacked permissions to read the `~/.sentryclirc` because I had ran `chmod 000 ~/.sentryclirc` prior to running the command you provided. The command appeared to run as expected when my user had read permissions on `~/.sentryclirc` file or when the `~/.sentryclirc` file did not exist. 

Can you please verify whether you actually have reading permissions on the `~/.sentryclirc` file?

**Comment by arielelkin** [comment]
@szokeasaurusrex ah, that was the issue. Fixing permissions resolved this. Thanks for your help.

**Comment by loftykhanna** [comment]
run chmod 705 .sentryclirc

**Comment by yspreen** [comment]
this is not fixing the issue for me.

**Comment by dr-star** [comment]
> this is not fixing the issue for me.

Try to send more details about your issue. Such as pasting the error logs. If possible set logs to DEBUG/INFO with "export SENTRY_LOG_LEVEL=debug" or "--log-level=debug"
if you have the issue from Xcode try checking https://github.com/getsentry/sentry-cli/issues/1902
