### ISSUE TITLE
'This event doesn't have a dist value' issue

### ISSUE THREAD

**Issue by dorin-flooz** [getsentry/sentry-cli#1892]
### Environment
_What version of the CLI and what OS are you running?_
sentry-cli: 2.24.1 / OS: ubuntu latest

### Steps to Reproduce
_What you did?_
Our sourcemaps are uploaded automatically when we run `yarn build`. Log output:
```> Found 280 release files
> Analyzing 280 sources
> Rewriting sources
> Adding source map references
> Bundled 280 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: f(...)
> Project: f(...)
> Release: 0.0.49
> Dist: ./.next
```

### Expected Result
_What you thought would happen?_
We expect to see unminified errors in Sentry

### Actual Result
_What actually happened?_
When we trigger an error from the `/sentry-example-page` route, we get:
`Stack Frame Not Matching Artifact Name
(...)
This event doesn't have a dist value. Please check that you uploaded your artifacts without dist value.`

In Settings > Project > [project] > Sourcemaps, these are the artifacts generated by our `yarn build` run above (some of them are incorrectly associated with a generated release - `fe66af...` - maybe this is the root cause for this issue?)
![image](https://github.com/getsentry/sentry-cli/assets/100676452/b4fc3d4d-e8cc-4a97-b37c-4ad0fdc4a60e)

**Comment by szokeasaurusrex** [comment]
Hi @dorin-flooz, based on the error message, it appears that you provided a distribution value via the `--dist` argument passed to the `sentry-cli sourcemaps upload` command when uploading the sourcemaps. When generating the sourcemaps with a `--dist` argument, you [must set the same `dist` value](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/legacy-uploading-methods/#verify-artifact-distribution-value-matches-value-configured-in-your-sdk) when initializing the SDK. However, based on your error message, it appears that that the `dist` argument is not provided when initializing the SDK.

You should probably be able to solve this problem by either running the `sentry-cli sourcemaps upload` command without any `--dist` argument. Another possible solution would be to pass the same `dist` argument when initializing the SDK as what you are passing to the CLI.

Hope this information helps! If it does, please close the issue; otherwise, please send me the command your `yarn build` script is running, so that I can attempt to reproduce this problem.

**Comment by dorin-flooz** [comment]
Actually we'd rather move away from the automatic upload happening on `yarn build`, since it seems harder to debug. We'd rather try to make it work by using `sentry-cli` in our CI/CD and providing the correct `dist`.

I made some changes to our scripts and this is our current setup:
- app is a NextJS app, deployed using GitHub Actions
- we use the following in our `sentry.edge.config.ts`, `sentry.edge.config.ts` and `sentry.server.config.ts`: 
```
Sentry.init({
    release: releaseVersion, // takes it from package.json > version, same as our CI/CD script
    dist: './.next',
    ...
});
```
- our next.config.js looks like this:
```
const nextConfig = {
...
    sentry: {
        hideSourceMaps: true,
        widenClientFileUpload: true,
        disableServerWebpackPlugin: true,
        disableClientWebpackPlugin: true,
    },
};

module.exports = () => {
    const sentryConfigs = withSentryConfig(nextConfig);
    return withBundleAnalyzer(nextTranslate(sentryConfigs));
};

```
- we use the following script in CI/CD:
```
-   name: Send release data to Sentry
    env:
    SENTRY_AUTH_TOKEN: (sentry token)
    SENTRY_URL: https://sentry.io
    run: |
    npm install -g @sentry/cli
    sentry-cli releases new ${{ version }} --org {{ org }} --project {{ project }} --log-level=debug
    sentry-cli releases set-commits --auto ${{ version }} --org {{ org }} --project {{ project }} --log-level=debug
    sentry-cli sourcemaps upload --release=${{ version }} .next/static --dist=./.next  --org {{ org }} --project {{ project }} --log-level=debug
```
- our CI/CD scripts outputs:
```
> Uploaded files to Sentry
> File upload complete (processing pending on server)
> Organization: f...
> Project: f...
> Release: 0.0.52
> Dist: ./.next
> Upload type: artifact bundle
```
but also some warnings:
```
  DEBUG   2024-01-09 08:33:07.699114479 +00:00 response status: 200
  DEBUG   2024-01-09 08:33:07.699127079 +00:00 body: {"state":"not_found","missingChunks":["9989cdd237ff77eca1238899a41845391d75b207"]}
(...)
Source Map Upload Report
  Scripts
    ~/42b3rAWblO1ZQLw0_-c4o/_ssgManifest.js
  Minified Scripts
    ~/42b3rAWblO1ZQLw0_-c4o/_buildManifest.js (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/42b3rAWblO1ZQLw0_-c4o/_buildManifest.js)
    ~/chunks/1011.9842cbd5b510e713.js (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/chunks/1011.9842cbd5b510e713.js)
```
- our errors still show: `Stack frame path doesn't match a source file artifact name. This event doesn't have a dist value`

I also tried using the setup above but removing `dist` from our sentry config and running the sentry-cli sourcemaps upload command without any --dist argument - had the same issue.

**Comment by szokeasaurusrex** [comment]
Hi @dorin-flooz, I noticed that you are setting `disableServerWebpackPlugin` and `disableClientWebpackPlugin` to `true` in your Sentry config. Is there any reason why you have decided to disable these? Enabling the server and client webpack plugins by removing these configuration options might solve your problem, since the Sentry webpack plugin automatically uploads sourcemaps by default unless you disable these plugins. Could you please try to enable these?

If you are using Sentry SaaS (sentry.io), and if you still are having trouble after removing the `disableServerWebpackPlugin` and `disableClientWebpackPlugin` configuration options, it would be very helpful if you could share the link to an event in Sentry where you observe this error message.

**Comment by dorin-flooz** [comment]
@szokeasaurusrex I've just started from scratch, just to get the basics to work - still no luck... 
So:
- I now ran `npx @sentry/wizard@latest -i nextjs` - it overwrote our next.config.js, sentry.client.config.ts, sentry.edge.config.ts, sentry.edge.config.ts. I kept all changes made by it.
- I then ran `yarn build` in our deployment pipeline - I got this output:
```
> Found 280 release files
> Analyzing 280 sources
> Rewriting sources
> Adding source map references
> Bundled 280 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: f(...)
> Project: f(...)
> Release: 0.0.55
> Dist: None
```
- Now, if I go to our sentry.io/releases page, I cannot find the release above - `0.0.55`, so I can't even isolate events to test this...

**Comment by szokeasaurusrex** [comment]
Hi @dorin-flooz, I am going to need some more information to be able to reproduce your issue. If your repository is public, could you share a link to it, so I can try out the commands you are running locally? If the repo is private, would you be able to create a minimal reproduction that you can share with me?

> Now, if I go to our sentry.io/releases page, I cannot find the release above - 0.0.55, so I can't even isolate events to test this...
Do you have any example errors from before you tried starting from scratch? If yes, it would be very helpful if you could share a link to them!

**Comment by dorin-flooz** [comment]
@szokeasaurusrex thank you for the help. I'll try to create a reproduction repro and share it with you.
In the meantime, here's a link to the example error:
[sentry-example-page error](https://flooz.sentry.io/issues/4772245775/?environment=pre-release&project=6405829&query=is%3Aunresolved+sentry&referrer=issue-stream&statsPeriod=14d&stream_index=0)
Each 0.0.x release linked to this error in this environment is a separate attempt we made with different combinations of Sentry configs / tools. If you can track down the Sentry problem in any of them, I can then redeploy that specific commit with your suggested fix.

**Comment by szokeasaurusrex** [comment]
@dorin-flooz Thanks for the information. Do you know what version of the `@sentry/webpack-plugin` you are using?

**Comment by dorin-flooz** [comment]
we have "@sentry/nextjs": "^7.92.0"
