### ISSUE TITLE
Release commits are currently being processed (http status: 409)

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry-cli#1928]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

See https://github.com/getsentry/sentry-cli/issues/1927 for the situation and setup. 

### How are you getting stuck?

Now in CI, A and B start their build jobs simultaneously and create a release (for the respective project), but I now get this error message from `sentry-cli releases set-commits $RELEASE --auto --ignore-missing`:

```
error: API request failed
  caused by: sentry reported an error: Release commits are currently being processed (http status: 409)
```

I'm not sure what the issue is. Can I only have a single project connected to a release name?

### Where in the product are you?

Releases

**Comment by szokeasaurusrex** [comment]
I left a question about your setup on the other issue you opened: https://github.com/getsentry/sentry-cli/issues/1927#issuecomment-1929035264. We will need to clarify the setup before I can help you with this issue.

**Comment by jeengbe** [comment]
Added a comment on the other issue 👍🏻

**Comment by szokeasaurusrex** [comment]
Okay! I will return to this issue once I can reproduce #1927

**Comment by szokeasaurusrex** [comment]
Hi @jeengbe, the problem is that you are running the `sentry-cli releases set-commits` commands in parallel from both build scripts. The `409` occurs because the backend cannot acquire the lock to update the release's commits while the backend is already setting the commits from the other time you ran the command.

You can fix the problem by ensure you don't run `sentry-cli releases set-commits` on the same release simultaneously. However, based on the output I received when I tried running the command for both projects in series (exact command and output copied below), I believe you should only need to run `sentry-cli releases set-commits` once for both projects, since the commits are only associated with the release, not with the project.

```
$ (cd project-1 && sentry-cli releases set-commits 1.0 --auto) && (cd project-2 && sentry-cli releases set-commits 1.0 --auto)
Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from local git tree.
Success! Set commits for release 1.0
Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from local git tree.
No commits found. Leaving release alone. If you believe there should be some, change commits range or initial depth and try again.
```

**Comment by jeengbe** [comment]
@szokeasaurusrex Thanks for investigating this!

This directly conflicts with information found in the documentation: [https://docs.sentry.io/product/cli/releases/](https://docs.sentry.io/product/cli/releases/#:~:text=Because%20releases%20work%20on%20projects%20you%20will%20need%20to%20specify%20the%20organization%20and%20project%20you%20are%20working%20with.)
> Because releases work on projects you will need to specify the organization and project you are working with.

How is this supposed to work? Do I create a release _per_ project, but then set the commits in a separate job once for all releases that happen to share the same name? That sounds very inconsistent.

**Comment by szokeasaurusrex** [comment]
@jeengbe Thank you for pointing that out – I am going to reopen this issue and #1927 and investigate further

**Comment by jeengbe** [comment]
Thanks for continuing this. I just had another look at the docs and source code (of Sentry CLI), and I'm not sure now which one it is. Let's close this issue as a duplicate and focus the discussion on #1927
