### ISSUE TITLE
Update pypi distribution

### ISSUE THREAD

**Issue by yml** [getsentry/sentry-cli#1931]
### Environment

The latest version of sentry-cli on pypi is 2.21.2. What is the process to get the newer version on pypi ?

![image](https://github.com/getsentry/sentry-cli/assets/125902/f7419508-367f-4fca-98ad-7043094c150e)

**Comment by szokeasaurusrex** [comment]
Hi @yml, thank you for bringing this problem to our attention.

It does appear that we [intentionally disabled](https://github.com/getsentry/sentry-cli/pull/1779#issue-1932742556) Python releases between versions 2.21.2 and 2.21.3 because the releases kept failing. However, according to the PR description, this change was meant to only be temporary.

I will investigate whether we can re-enable Python releases now and will get back to you once I have more information. In the meantime, you can obtain the latest version by using a different [installation method](https://docs.sentry.io/product/cli/installation/).

**Comment by szokeasaurusrex** [comment]
We have fixed this already and neglected to close the issue. New Sentry-CLI releases should be getting pushed to pypi
