### ISSUE TITLE
Code with side-effects is injected into JS chunks.

### ISSUE THREAD

**Issue by koddsson** [getsentry/sentry-cli#1950]
The Sentry CLI is injecting the following code at the top of our JS assets.

`!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="e578340b-5627-493b-9bef-a3e67db3d4b9")}catch(e){}}();`

I'm not 100% what the reason is since the debugid is already injected at the bottom of the file as a  comment.

The trouble is that this code is side-effectful which causes our bundler to include these chunks in a bunch of other chucks even though it's not needed. Is it possible to opt-out of this JS snippet and just rely on the sourcemap comment? I'd like to not inject any runtime code into our chunks at all.

**Comment by koddsson** [comment]
Actually as soon as I hit "Open Issue" it occurs to me that we inject the chunks after building so it's not possible for the sentry code to have a effect on the bundling. I'mma close this in embarrassment :D

**Comment by vanschelven** [comment]
Just because the OP isn't affected in the way they thought, doesn't mean this isn't an issue 😄 

I'd say the issue is:

Some magical code is added to the top of the minified files, but this is completely undocumented.

* [Here's the spec](https://github.com/tc39/ecma426/blob/main/proposals/debug-id.md) which Sentry had a big part in proposing, but which this does not adhere to.
* [Here's how the command should be verified](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/#verify-debug-ids-were-injected-in-artifacts) but it does more

**Comment by vanschelven** [comment]
Best hint I could find at what this might do is here: https://github.com/getsentry/sentry-cli/issues/1467
