### ISSUE TITLE
sourcemaps explain says no files uploaded though artifact bundle has been uploaded

### ISSUE THREAD

**Issue by broksonic21** [getsentry/sentry-cli#2071]
### CLI Version

sentry-cli 2.31.2

### Operating System and Architecture

- [X] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macOS 14.5.0

### CLI Command

npx sentry-cli sourcemaps explain REDACTED

### Exact Reproduction Steps

- Use sentry-webpack-plugin to upload packages
- Look at sentry (self-hosted) and see that there are in fact artifact bundles uploaded, associated with a release. Note: there are no _release bundles_
- run `npx sentry-cli sourcemaps explain REDACTED`.... get these lines:

```
⚠ DEPRECATION: `sourcemaps explain` has drifted from how sourcemap processing actually operates and its output may not be accurate. It will be removed in a future version of `sentry-cli`.
✔ Fetched data for event: REDACTED
✔ Event has release name: REDACTED
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✖ Release has no artifacts uploaded
```

For deprecation, followup to [https://github.com/getsentry/sentry-cli/issues/2070](https://github.com/getsentry/sentry-cli/issues/2070)

### Expected Results

sourcemap explain is artifacts bundle aware and doesn't say no artifacts uploaded if there were in fact

### Actual Results

says no artifacts uploaded

It seems to be looking at "files" in the API - the last call is to files

  DEBUG   2024-05-23 10:25:00.156782 -04:00 request GET https://REDACTED/api/0/projects/sentryREDACTED/releases/REDACTED/files/?cursor=

### Logs

see above

**Comment by TzviPM** [comment]
I saw a similar issue as well, but, in my case, the artifact bundle was uploaded but no actual files were uploaded.

**Comment by szokeasaurusrex** [comment]
As I explained in my response to #2070, the `sourcemaps explain` command is deprecated. As stated in the deprecation notice, the command may produce inaccurate output, and therefore, we do not recommend using the command.

If I understand the issue correctly, it seems like everything is working, except for `sourcemaps explain`. Since we no longer support `sourcemaps explain`, I will go ahead and close this issue. If I misunderstood something, and there is in fact some issue outside of just `sourcemaps explain`, please re-open the issue and explain.
