### ISSUE TITLE
Getting error about different URL values supplied after upgrading Sentry client from v7 to v8 in a Next.js application

### ISSUE THREAD

**Issue by carestad** [getsentry/sentry-cli#2089]
### CLI Version

2.32.1

### Operating System and Architecture

- [ ] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [X] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

Pop!_OS 22.04 LTS

### CLI Command

sentry-cli releases new jZVTDPTCSwNIkTsgMlnSn

### Exact Reproduction Steps

1. Upgraded Sentry from v7 to v8 for my next.js application, following the guide [here](https://docs.sentry.io/platforms/javascript/guides/nextjs/migration/v7-to-v8/)
2. Ran `npm run build` in my next.js application

### Expected Results

Expected build to go through and work okay.

### Actual Results

Error shown regarding different URL values, which I have never seen previously.

### Logs

```
unhandledRejection Error: Command failed: /my/nextjs/application/node_modules/@sentry/cli-linux-x64/bin/sentry-cli releases new 1LtZEu3zkB0uhzqaJDFJ_
error: Two different url values supplied: `https://sentry.xyz` (from token), `https://sentry.io`.
```

**Comment by szokeasaurusrex** [comment]
Hi @carestad, you are likely setting the URL to `https://sentry.io` somewhere in the configuration for the Sentry bundler plugin. Since the URL value is different from the URL encoded in your auth token, you are getting an error. Since the auth token already contains the URL, you do not need to manually provide it, so I would recommend removing the URL option from your configurations.

Please let me know whether that fixes your problem!
