### ISSUE TITLE
Add support for App Center CLI in addition to CodePush

### ISSUE THREAD

**Issue by bslayerw** [getsentry/sentry-cli#218]
```$ sentry-cli --version
sentry-cli 1.28.1
```

Following the documentation located here: https://docs.sentry.io/clients/react-native/codepush/. I cannot get sentry-cli to work without me specifying parameters explictly. They don't seem to be picked up from the sentry.properties file I specify with `ENTRY_PROPERTIES=./ios/sentry.properties`.

When I specify the parameters I get the following error: 

```


sentry-cli react-native codepush --org myorg --project myproject  myCodePushProjectName ./build
> Fetching latest code-push package info
error: No such file or directory (os error 2)
```

**Comment by jan-auer** [comment]
Hi @bslayerw, 

 - Is this just a typo here or did you declare the environment variable as `ENTRY_PROPERTIES`? 
 - Please make sure that the `code-push` binary is on the `PATH`. Assuming it is somewhere in `node_modules`, we will update `sentry-cli` to check there, too.
 - FWIW, the command you posted here is missing the platform argument before the path (`android` or `ios`). But judging by the output you used it when you ran locally.

**Comment by bslayerw** [comment]
@jan-auer code push is definetly in my path or I would not get the following output `> Fetching latest code-push package info`. Here's another command I tried with the same error: 

`SENTRY_PROPERTIES=./ios/sentry.properties ./node_modules/@sentry/cli/bin/sentry-cli react-native codepush  myCodePushProjectName ios ./build`

`> Fetching latest code-push package info
error: No such file or directory (os error 2)`

**Comment by bslayerw** [comment]
okay I think I figured it out. Code push is probably not in my path because I'm using the new appcenter cli. I guess sentry-cli doesn't support the new appcenter cli yet? Making a note here for others who might bump into this.

**Comment by jan-auer** [comment]
Sorry, did not mean to close this via the issue. You are correct, we do not support the App Center CLI just yet. Sorry for the inconvenience and let us keep this open until we've added support for App Center.

In the meanwhile, the linked PR (#220) tries to improve the error messages to make this more clear. "Fetching latest code-push package info" simply meant that `sentry-cli` is trying to invoke codepush.

**Comment by HAMPLENI** [comment]
Same situation for me.  I would prefer to use the App Center CLI except I cannot.  When I try to use the CodePush CLI, I still have not been able to resolve the error unlike bslayerw.

* OS: Windows 10
* Using nvm-windows
* npm@3.10.10
* node@6.11.1
* sentry-cli@1.25.0
* Platform: Android
* Git Bash Running as Administrator
* Running from root project directory (contains the android folder)
* Added C:\ProgramData\nvm\v6.11.1, which contains the code-push binary, to my PATH Environment Variable.

Running `sentry-cli react-native codepush ...` prints the following to the console before the error:

`> Fetching latest code-push package info
error: The system cannot find the file specified. (os error 2)`

It seems it does not matter what I pass for the other arguments; this error always occurs.

Nothing else prints to the console.

I have tried globally npm installing sentry-cli-binary and code-push.  I have also tried using ./node_modules/sentry-cli-binary/bin/sentry-cli, which is also on version 1.25.0.

I tried globally installing @sentry/cli as an administrator in order to try to use that instead but I kept getting a "spawn EBUSY" error.  I followed the steps here:

https://github.com/getsentry/sentry-cli#node

I am not able to use `sudo` in Git Bash.

**Comment by jan-auer** [comment]
We've added an appcenter command in version 1.33.0. The react native SDK will follow soon. Note that you have to specify the entire appcenter app name including your user slug (e.g. `myuser/myapp`):

```
Upload react-native projects for AppCenter.

USAGE:
    sentry-cli react-native appcenter [OPTIONS] <APP_NAME> <PLATFORM> <PATH>...

OPTIONS:
        --bundle-id <BUNDLE_ID>      Explicitly provide the bundle ID instead of parsing the source
                                     projects.  This allows you to push codepush releases for iOS on
                                     platforms without Xcode or codepush releases for Android when
                                     you use different bundle IDs for release and debug etc.
        --deployment <DEPLOYMENT>    The name of the deployment. [Production, Staging]
    -h, --help                       Prints help information
    -o, --org <ORG>                  The organization slug
        --print-release-name         Print the release name instead.
    -p, --project <PROJECT>          The project slug
    -V, --version                    Prints version information

ARGS:
    <APP_NAME>    The name of the AppCenter application.
    <PLATFORM>    The name of the app platform. [ios, android]
    <PATH>...     A list of folders with assets that should be processed.
```

**Comment by acomito** [comment]
@jan-auer I love appcenter and sentry so I was glad to see your announcement here. 

My current react-native app has an npm script for codepush that is really simple. It looks like this:

```
"codepush-staging" : "appcenter codepush release-react -a Organization/MyApp -d Staging",
```
To add the sentry feature you mention, I would essentially run the above command, and then after I can run an addition npm script (or maybe shell scrip) like the below?

```
"sentry-staging" : "sentry-cli react-native appcenter --org Organization --deployment Staging MyApp",
```

Is <PATH> required? Should that point to source maps or can he cli figure it out by itself?

**Comment by lucianomlima** [comment]
Please update docs!
