### ISSUE TITLE
无法定位程序输入点ProcessPrng于动态链接库bcryptprimitives.dll

### ISSUE THREAD

**Issue by pan1997121** [getsentry/sentry-cli#2211]
### CLI Version

2.8.2

### Operating System and Architecture

- [ ] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [x] Windows (x86_64)

### Operating System Version

windows 2008 r2

### Exact Reproduction Steps

直接执行exe文件

### Expected Results

无法定位程序输入点ProcessPrng于动态链接库bcryptprimitives.dll

### Actual Results

![Image](https://github.com/user-attachments/assets/3875182f-f8a2-4475-b3e2-16e96ef32c94)

### Logs

no

**Comment by szokeasaurusrex** [comment]
Hi @pan1997121, thank you for the issue.

We do not officially support Windows 2008, since it is a very old version of Windows. So, I cannot really help you here.

You could try using the [latest version of Sentry CLI](https://github.com/getsentry/sentry-cli/releases/tag/2.38.2). It contains a fix that might help here. But, if that does not work, then Sentry CLI is probably just not compatible with Windows 2008.
