### ISSUE TITLE
How to use it in nodejs?

### ISSUE THREAD

**Issue by BlackHole1** [getsentry/sentry-cli#344]
my code:

```javascript
const exec = require('child_process').exec;
const path = require('path');

exec(`${path.join(__dirname, '..', 'node_modules', '.bin', 'sentry-cli')} info`, (e, o) => {
  console.log(e, o);
});
```

output:

```
{ Error: Command failed: /Users/black-hole/Code/Job/test/packages/test/node_modules/.bin/sentry-cli info

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/Users/black-hole/Code/Job/test/packages/test/node_modules/.bin/sentry-cli info' } 'Sentry Server: https://sentry.io\nDefault Organization: -\nDefault Project: -\n\nAuthentication Info:\n  Method: Auth Token\n  User: 158blackhole@gmail.com\n  Scopes:\n    - project:read\n    - project:releases\n'
```

From the result, it is correct, but why is it wrong?

**Comment by jan-auer** [comment]
The file you're trying to spawn is actually a NodeJS script. It is declared [here](https://github.com/getsentry/sentry-cli/blob/a3c98dbe1047993aac4825103a053fff2028793c/bin/sentry-cli). In case you're trying to manage releases from JavaScript, you can simply use our node wrapper:

```js
const SentryCli = require('@sentry/cli');
const cli = new SentryCli();
await cli.releases.new(release);
...
```

We only use this internally, which is why there is not much documentation around this feature. You should be able to figure out the command by looking at [the source](https://github.com/getsentry/sentry-cli/blob/a3c98dbe1047993aac4825103a053fff2028793c/js/releases/index.js).

If the command you're looking for is not implemented, we export the path to the actual executable with a utility function:

```js
const execFile = require('child_process').execFile;
const sentryCliPath = require('@sentry/cli').getPath();
execFile(sentryCliPath, ['info'], /* ... */)
```

**Comment by BlackHole1** [comment]
Thank you very much!
Because we need to upload `Debug Information Files` in gitlab-ci. So we need to do it in JS.
