### ISSUE TITLE
Error "Failed to load AppCenter deployment history" with react-native appcenter on Windows

### ISSUE THREAD

**Issue by jer-sen** [getsentry/sentry-cli#415]
When I run this command: `sentry-cli react-native appcenter --print-release-name -o sentryorg -p sentryproject --deployment Staging cporg/cpapp android .\codePushOutput`

I get this error:

```
error: Failed to load AppCenter deployment history
  caused by:
```

I'm on Windows 10 with appcenter-cli installed globally. Sentry CLI run the right appcenter.cmd with the right arguments: `codepush deployment history Staging --app cporg/cpapp --output json`

When I run `appcenter codepush deployment history Staging --app cporg/cpapp --output json` everything is ok.

@sentry/cli@1.36.1
appcenter-cli@1.1.4

**Comment by macc1992** [comment]
I have the same problem with you and I try to use both powershell and CMD to run the command.
The result same as you and it is fine when using the codepush command independently

@sentry/cli@1.36.2
appcenter-cli@1.1.4
Win 10 Home 1803 Version 17134.345

**Comment by macc1992** [comment]
I am same with you and I use both powershell and CMD to run under both user and admin mode.
The result is the same with the appcenter command run itself is fine.

I am using node 8.12

 Package list at npm list -g --depth=0:

+-- @sentry/cli@1.36.2
+-- appcenter@1.8.1
+-- appcenter-cli@1.1.4
-- react-native-cli@2.0.1

Win 10 Home 1803 Version 17134.345

**Comment by macc1992** [comment]
Current bypass is using Linux Subsystem for windows and I install ubuntu on windows, node and appcenter-cli and sentry/cli.
You can access windows file and folder by /mnt/(drive letter)

**Comment by fungilation** [comment]
This is still happening on the latest appcenter-cli and sentry-cli. On Windows 10. Fix please?

**Comment by abunsen** [comment]
Are there any updates on this?

**Comment by SiSa68** [comment]
Any news?!

**Comment by Legi0n1138** [comment]
Still an issue on the latest version

**Comment by shangyilim-hubble** [comment]
For my case, i followed  the documentation in https://docs.sentry.io/platforms/react-native/codepush/, and got the same error. After digging through the codebase, this is how it gets the project 
`appcenter  codepush deployment history <DEPLOYMENT_NAME>  --app <APP_NAME> --output json`

Turns out the documentation did not mention that if your codepush runs on different deployment names other than `Staging` it doesnt work. So for me what worked was adding the `--deployment <DEPLOYMENT_NAME>`

**Comment by kamilogorek** [comment]
Thanks @shangyilim-hubble ! 

Updated our docs, which should resolve the original issue - https://github.com/getsentry/sentry-docs/pull/2001

Cheers!

**Comment by icecapp** [comment]
Neither of these work for me either, getting the same error

**Comment by samal-rasmussen** [comment]
Yeah I got this error when running sentry-cli on our build server, but not locally. Turns out it was because I logged into appcenter locally using `appcenter login`, but this doesn't make sense on our build server, so it wasn't logged in and got rejected.

The appcenter cli does read an environment variable for the token:
https://docs.microsoft.com/en-us/appcenter/cli/#logging-in

After setting this environment variable the error went away and sentry-cli ran successfully.

**Comment by samal-rasmussen** [comment]
I was about to see if I could get some actual useful information logged about that error, but then I figured out what our problem was, and so I didn't go forward with that. The error message is being swallowed here: https://github.com/getsentry/sentry-cli/blob/e08e7c31d93a29797edf7d1e5ec42ee0453ecc49/src/utils/appcenter.rs#L133

**Comment by kamilogorek** [comment]
@samal-rasmussen are you using the latest release? I fixed this issue already: https://github.com/getsentry/sentry-cli/commit/bb570876b61ec72fbe4ed32bfb2a0b32882e789b

**Comment by kopax-polyconseil** [comment]
I got the same error and this are the version I use for Sentry with react-native 0.68.0

```ts
{
    "@sentry/react": "^7.6.0",
    "@sentry/react-native": "^4.1.2",
    "@sentry/tracing": "^7.6.0",
    "@sentry/types": "^7.6.0",
    "@sentry/webpack-plugin": "^1.18.9"
}
````
