### ISSUE TITLE
Sentry CLI Plugin: stderr maxBuffer exceeded

### ISSUE THREAD

**Issue by qianL93** [getsentry/sentry-cli#460]
https://github.com/getsentry/sentry-cli/blob/8c28e7dec05347f589096c7020425ffb5742f7e9/js/helper.js#L144

"stderr maxBuffer exceeded" error occurs when executing `uploadSourceMaps`. The cause of this error is not clear. Maybe there are too many files in my dist folder, and `childProcess.execFile` will get a default `maxBuffer ` (200*1024).

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since, as we changed how curl is linked in the binary, and it may have an effect here as well.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
