### ISSUE TITLE
skipping update nagger because session is not attended

### ISSUE THREAD

**Issue by crobinson42** [getsentry/sentry-cli#547]
I'm having this issue suddenly after bumping patch versions on a dozen or so npm deps for my react-native project - it runs fine locally but I get this issue in Jenkins... (we are using a cloud/paid Sentry account)

TLDR:
```
> Bundled 2 files for upload
  DEBUG   2019-06-10 22:42:07.398706104 +00:00 error: running update nagger
  DEBUG   2019-06-10 22:42:07.398747804 +00:00 skipping update nagger because session is not attended
error: API request failed
  caused by: [55] Failed sending data to the peer
  DEBUG   2019-06-10 22:42:07.399649603 +00:00 client close; no transport to shut down  (from sentry)
```

full output
```
> Task :app:bundleReleaseJsAndAssets_SentryUpload
  INFO    2019-06-10 22:41:32.546500441 +00:00 Loaded config from /root/.sentryclirc
  DEBUG   2019-06-10 22:41:32.546559456 +00:00 sentry-cli version: 1.44.3, platform: "linux", architecture: "x86_64"
  INFO    2019-06-10 22:41:32.546587284 +00:00 sentry-cli was invoked with the following command line: "/var/jenkins_home/workspace/HHS2_hhs2-228/node_modules/@sentry/cli/sentry-cli" "--log-level" "debug" "react-native" "gradle" "--bundle" "/var/jenkins_home/workspace/HHS2_hhs2-228/android/app/build/generated/assets/react/release/index.android.bundle" "--sourcemap" "/var/jenkins_home/workspace/HHS2_hhs2-228/android/app/build/generated/assets/react/release/index.android.bundle.map" "--release" "com.hhs2-1.0.0" "--dist" "2107152" "--dist" "1058576"
  INFO    2019-06-10 22:41:32.551423930 +00:00   bundle path: /var/jenkins_home/workspace/HHS2_hhs2-228/android/app/build/generated/assets/react/release/index.android.bundle
  INFO    2019-06-10 22:41:32.551453778 +00:00   sourcemap path: /var/jenkins_home/workspace/HHS2_hhs2-228/android/app/build/generated/assets/react/release/index.android.bundle.map
  DEBUG   2019-06-10 22:41:32.551495316 +00:00 Non-file bundle found
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
  DEBUG   2019-06-10 22:41:33.162215671 +00:00 request POST https://sentry.io/api/0/projects/sscs-a4/rn-hhs2/releases/
  DEBUG   2019-06-10 22:41:33.162242200 +00:00 using token authentication
  DEBUG   2019-06-10 22:41:33.162253937 +00:00 json body: {"version":"com.hhs2-1.0.0","projects":["rn-hhs2"]}
  DEBUG   2019-06-10 22:41:33.162262487 +00:00 retry number 0, max retries: 0
  DEBUG   2019-06-10 22:41:33.338939490 +00:00 > POST /api/0/projects/sscs-a4/rn-hhs2/releases/ HTTP/1.1
  DEBUG   2019-06-10 22:41:33.338967902 +00:00 > Host: sentry.io
  DEBUG   2019-06-10 22:41:33.338973739 +00:00 > Accept: */*
  DEBUG   2019-06-10 22:41:33.338980737 +00:00 > Connection: TE
  DEBUG   2019-06-10 22:41:33.338985809 +00:00 > TE: gzip
  DEBUG   2019-06-10 22:41:33.338990720 +00:00 > User-Agent: sentry-cli/1.44.3
  DEBUG   2019-06-10 22:41:33.339447883 +00:00 > Authorization: Bearer f805e045***
  DEBUG   2019-06-10 22:41:33.339456408 +00:00 > Content-Type: application/json
  DEBUG   2019-06-10 22:41:33.339461904 +00:00 > Content-Length: 51
  DEBUG   2019-06-10 22:41:33.582809438 +00:00 < HTTP/1.1 208 ALREADY REPORTED
  DEBUG   2019-06-10 22:41:33.582841547 +00:00 < Server: nginx
  DEBUG   2019-06-10 22:41:33.582851184 +00:00 < Date: Mon, 10 Jun 2019 22:41:33 GMT
  DEBUG   2019-06-10 22:41:33.582858650 +00:00 < Content-Type: application/json
  DEBUG   2019-06-10 22:41:33.582866393 +00:00 < Content-Length: 466
  DEBUG   2019-06-10 22:41:33.582877205 +00:00 < Connection: keep-alive
  DEBUG   2019-06-10 22:41:33.582886866 +00:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2019-06-10 22:41:33.582896674 +00:00 < Content-Language: en
  DEBUG   2019-06-10 22:41:33.582921078 +00:00 < X-Content-Type-Options: nosniff
Uploading sourcemaps for release com.hhs2-1.0.0 distribution 2107152
  DEBUG   2019-06-10 22:41:33.582930234 +00:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-06-10 22:41:33.582940300 +00:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2019-06-10 22:41:33.582949070 +00:00 < X-Frame-Options: deny
  DEBUG   2019-06-10 22:41:33.582954901 +00:00 < X-Served-By: web-b378b859
  DEBUG   2019-06-10 22:41:33.582962157 +00:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2019-06-10 22:41:33.582993037 +00:00 response status: 208
  DEBUG   2019-06-10 22:41:33.583005531 +00:00 body: {"dateReleased": null, "commitCount": 0, "url": null, "data": {}, "lastDeploy": null, "deployCount": 0, "dateCreated": "2019-02-11T19:43:27.912Z", "lastEvent": "2019-05-29T17:09:24Z", "version": "com.hhs2-1.0.0", "firstEvent": "2019-05-28T20:23:51Z", "lastCommit": null, "shortVersion": "1.0.0", "authors": [], "owner": null, "newGroups": 173, "ref": null, "projects": [{"slug": "rn-hhs2", "name": "RN-HHS2"}, {"slug": "cstoreitemsweb", "name": "CSTORE.ITEMS.WEB"}]}
  DEBUG   2019-06-10 22:41:33.583132624 +00:00 request GET https://sentry.io/api/0/organizations/sscs-a4/chunk-upload/
  DEBUG   2019-06-10 22:41:33.583142762 +00:00 using token authentication
  DEBUG   2019-06-10 22:41:33.583148890 +00:00 retry number 0, max retries: 0
  DEBUG   2019-06-10 22:41:33.583267698 +00:00 > GET /api/0/organizations/sscs-a4/chunk-upload/ HTTP/1.1
  DEBUG   2019-06-10 22:41:33.583276448 +00:00 > Host: sentry.io
  DEBUG   2019-06-10 22:41:33.583281916 +00:00 > Accept: */*
  DEBUG   2019-06-10 22:41:33.583287363 +00:00 > Connection: TE
  DEBUG   2019-06-10 22:41:33.583292697 +00:00 > TE: gzip
  DEBUG   2019-06-10 22:41:33.583298030 +00:00 > User-Agent: sentry-cli/1.44.3
  DEBUG   2019-06-10 22:41:33.583347900 +00:00 > Authorization: Bearer f805e045***
  DEBUG   2019-06-10 22:41:33.667946969 +00:00 < HTTP/1.1 200 OK
  DEBUG   2019-06-10 22:41:33.667988844 +00:00 < Server: nginx
  DEBUG   2019-06-10 22:41:33.668001946 +00:00 < Date: Mon, 10 Jun 2019 22:41:33 GMT
  DEBUG   2019-06-10 22:41:33.668010303 +00:00 < Content-Type: application/json
  DEBUG   2019-06-10 22:41:33.668018125 +00:00 < Content-Length: 283
  DEBUG   2019-06-10 22:41:33.668025733 +00:00 < Connection: keep-alive
  DEBUG   2019-06-10 22:41:33.668032288 +00:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2019-06-10 22:41:33.668039270 +00:00 < Content-Language: en
  DEBUG   2019-06-10 22:41:33.668045830 +00:00 < X-Content-Type-Options: nosniff
  DEBUG   2019-06-10 22:41:33.668053173 +00:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-06-10 22:41:33.668068278 +00:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2019-06-10 22:41:33.668074874 +00:00 < X-Frame-Options: deny
  DEBUG   2019-06-10 22:41:33.668081534 +00:00 < X-Served-By: web-17b74f97
  DEBUG   2019-06-10 22:41:33.668088966 +00:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2019-06-10 22:41:33.668112487 +00:00 response status: 200
  DEBUG   2019-06-10 22:41:33.668121988 +00:00 body: {"maxFileSize": 2147483648, "hashAlgorithm": "sha1", "concurrency": 8, "chunkSize": 8388608, "maxRequestSize": 33554432, "url": "https://sentry.io/api/0/organizations/sscs-a4/chunk-upload/", "chunksPerRequest": 64, "accept": ["debug_files", "release_files"], "compression": ["gzip"]}
> Bundled 2 files for upload
  DEBUG   2019-06-10 22:42:07.398706104 +00:00 error: running update nagger
  DEBUG   2019-06-10 22:42:07.398747804 +00:00 skipping update nagger because session is not attended
error: API request failed
  caused by: [55] Failed sending data to the peer
  DEBUG   2019-06-10 22:42:07.399649603 +00:00 client close; no transport to shut down  (from sentry)
```

**Comment by jan-auer** [comment]
This output is a bit misleading, but the error is not due to the update nagger but due to the failed sourcemap upload. After that, but before printing the error message, it runs our update nagger which decides not to do anything.

Thanks for reporting, closing in favor of #514

**Comment by elviin** [comment]
I am also experiencing a similar issue:
sentry-cli 1.47.1

I also use a fastlane script on cirlcleCi, but with the same results. 

`
  DEBUG   2019-08-20 13:59:37.218202 +02:00 request POST https://sentry.flfinteche.de/api/0/projects/sentry/swift/files/dsyms/
  DEBUG   2019-08-20 13:59:37.218222 +02:00 using token authentication
  DEBUG   2019-08-20 13:59:37.218235 +02:00 sending form data
  DEBUG   2019-08-20 13:59:37.218243 +02:00 retry number 0, max retries: 0
  DEBUG   2019-08-20 13:59:37.218414 +02:00 > POST /api/0/projects/sentry/swift/files/dsyms/ HTTP/1.1
  DEBUG   2019-08-20 13:59:37.218425 +02:00 > Host: sentry.flfinteche.de
  DEBUG   2019-08-20 13:59:37.218433 +02:00 > Accept: */*
  DEBUG   2019-08-20 13:59:37.218440 +02:00 > Connection: TE
  DEBUG   2019-08-20 13:59:37.218448 +02:00 > TE: gzip
  DEBUG   2019-08-20 13:59:37.218454 +02:00 > User-Agent: sentry-cli/1.47.1
  DEBUG   2019-08-20 13:59:37.218482 +02:00 > Authorization: Bearer b74d7c9b***
  DEBUG   2019-08-20 13:59:37.218491 +02:00 > Content-Length: 2126377
  DEBUG   2019-08-20 13:59:37.218499 +02:00 > Content-Type: multipart/form-data; boundary=------------------------2768ad73b5593382
  DEBUG   2019-08-20 13:59:42.202366 +02:00 < HTTP/1.1 500 Internal Server Error
  DEBUG   2019-08-20 13:59:42.202400 +02:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2019-08-20 13:59:42.202411 +02:00 < Content-Language: en
  DEBUG   2019-08-20 13:59:42.202421 +02:00 < Content-Type: application/json
  DEBUG   2019-08-20 13:59:42.202431 +02:00 < Date: Tue, 20 Aug 2019 11:59:42 GMT
  DEBUG   2019-08-20 13:59:42.202440 +02:00 < Vary: Accept-Encoding
  DEBUG   2019-08-20 13:59:42.202448 +02:00 < Vary: Accept-Language, Cookie
  DEBUG   2019-08-20 13:59:42.202456 +02:00 < X-Content-Type-Options: nosniff
  DEBUG   2019-08-20 13:59:42.202464 +02:00 < X-Frame-Options: deny
  DEBUG   2019-08-20 13:59:42.202475 +02:00 < X-Xss-Protection: 1; mode=block
  DEBUG   2019-08-20 13:59:42.202484 +02:00 < Content-Length: 75
  DEBUG   2019-08-20 13:59:42.202493 +02:00 < Connection: keep-alive
  DEBUG   2019-08-20 13:59:42.203427 +02:00 response status: 500
  DEBUG   2019-08-20 13:59:42.203452 +02:00 body: {"detail": "Internal Error", "errorId": "4b9a84d9e96e4effa868e98f3882301d"}
  DEBUG   2019-08-20 13:59:42.205607 +02:00 error: running update nagger
  DEBUG   2019-08-20 13:59:42.206023 +02:00 skipping update nagger because session is not attended
`

**Comment by beyondouyuan** [comment]
> I am also experiencing a similar issue:
> sentry-cli 1.47.1
> 
> I also use a fastlane script on cirlcleCi, but with the same results.
> 
> DEBUG 2019-08-20 13:59:37.218202 +02:00 request POST
> DEBUG 2019-08-20 13:59:37.218222 +02:00 using token authentication
> DEBUG 2019-08-20 13:59:37.218235 +02:00 sending form data
> DEBUG 2019-08-20 13:59:37.218243 +02:00 retry number 0, max retries: 0
> DEBUG 2019-08-20 13:59:37.218414 +02:00 > POST /api/0/projects/sentry/swift/files/dsyms/
> HTTP/1.1
> DEBUG 2019-08-20 13:59:37.218425 +02:00 > Host: sentry......
> DEBUG 2019-08-20 13:59:37.218433 +02:00 > Accept: _/_
> DEBUG 2019-08-20 13:59:37.218440 +02:00 > Connection: TE
> DEBUG 2019-08-20 13:59:37.218448 +02:00 > TE: gzip
> DEBUG 2019-08-20 13:59:37.218454 +02:00 > User-Agent: sentry-cli/1.47.1
> DEBUG 2019-08-20 13:59:37.218482 +02:00 > Authorization: Bearer b74d7c9b***
> DEBUG 2019-08-20 13:59:37.218491 +02:00 > Content-Length: 2126377
> DEBUG 2019-08-20 13:59:37.218499 +02:00 > Content-Type: multipart/form-data; boundary=------------------------2768ad73b5593382
> DEBUG 2019-08-20 13:59:42.202366 +02:00 < HTTP/1.1 500 Internal Server Error
> DEBUG 2019-08-20 13:59:42.202400 +02:00 < Allow: GET, POST, HEAD, OPTIONS
> DEBUG 2019-08-20 13:59:42.202411 +02:00 < Content-Language: en
> DEBUG 2019-08-20 13:59:42.202421 +02:00 < Content-Type: application/json
> DEBUG 2019-08-20 13:59:42.202431 +02:00 < Date: Tue, 20 Aug 2019 11:59:42 GMT
> DEBUG 2019-08-20 13:59:42.202440 +02:00 < Vary: Accept-Encoding
> DEBUG 2019-08-20 13:59:42.202448 +02:00 < Vary: Accept-Language, Cookie
> DEBUG 2019-08-20 13:59:42.202456 +02:00 < X-Content-Type-Options: nosniff
> DEBUG 2019-08-20 13:59:42.202464 +02:00 < X-Frame-Options: deny
> DEBUG 2019-08-20 13:59:42.202475 +02:00 < X-Xss-Protection: 1; mode=block
> DEBUG 2019-08-20 13:59:42.202484 +02:00 < Content-Length: 75
> DEBUG 2019-08-20 13:59:42.202493 +02:00 < Connection: keep-alive
> DEBUG 2019-08-20 13:59:42.203427 +02:00 response status: 500
> DEBUG 2019-08-20 13:59:42.203452 +02:00 body: {"detail": "Internal Error", "errorId": "4b9a84d9e96e4effa868e98f3882301d"}
> DEBUG 2019-08-20 13:59:42.205607 +02:00 error: running update nagger
> DEBUG 2019-08-20 13:59:42.206023 +02:00 skipping update nagger because session is not attended

I am also the problem, i can't solve it




  DEBUG   2019-12-03 20:44:10.570344247 +08:00 body: []
> Uploading source maps for release 7ef13fdfa1b9ae02ca8aac75846f1ac568496ae4
  DEBUG   2019-12-03 20:44:10.694294876 +08:00 skipping update nagger because session is not attended

Source Map Upload Report
  Minified Scripts
    http://127.0.0.1:7002/zijia/book/static/js/zhima.261bee8f.js (sourcemap at zhima.261bee8f.js.map)
  Source Maps
    http://127.0.0.1:7002/zijia/book/static/js/zhima.261bee8f.js.map
Finalized release 7ef13fdfa1b9ae02ca8aac75846f1ac568496ae4.

**Comment by danielthank** [comment]
I had exactly the same issue. I solved it by adding
```
[http]
keepalive=false
```
in `.sentryclirc`

I god the idea from https://github.com/getsentry/sentry-cli/issues/40

**Comment by ariannargesi** [comment]
Same Issue here

**Comment by szokeasaurusrex** [comment]
@ariannargesi, since this is an old thread, I will ask you to please open a new bug report issue describing the problem you are experiencing
