### ISSUE TITLE
[Breaking change] React Native symbol upload iOS now requires version name parameter

### ISSUE THREAD

**Issue by squirly** [getsentry/sentry-cli#554]
Previously only `--bundle-id` was required when running in a non macOS environment, now `--version-name` is also required.

Error after upgrading:
```
$ sentry-cli "react-native" "appcenter" "-o" "storr" "-p" "mobile" "--deployment" "master" "--bundle-id" "app.storr" "storr/app.storr-ios" "ios" "./build/ios/CodePush"

> Fetching latest AppCenter deployment info
error: AppCenter codepush releases for iOS require macOS if no bundle ID is specified
```

Code where this is checked
https://github.com/getsentry/sentry-cli/blob/585f41ea4b7c0e6f1a1a591c56fffa649f6a6070/src/utils/appcenter.rs#L138-L143

Change introduced in https://github.com/getsentry/sentry-cli/commit/585f41ea4b7c0e6f1a1a591c56fffa649f6a6070#diff-8e4c8496f8f401a0cebfddf00bcdc705R138

The following line is now being triggered because the above condition is no longer being met:
https://github.com/getsentry/sentry-cli/blob/585f41ea4b7c0e6f1a1a591c56fffa649f6a6070/src/utils/appcenter.rs#L147

At a minimum, the above error should be updated; and this breaking change should be added to the changelog (version 1.44.4), to prevent future confusion.

**Comment by tonyo** [comment]
@squirly 
This was totally not meant to be a breaking change (our bad). 
We'll look into this, sorry for the confusion.

**Comment by squirly** [comment]
No worries. Let me know if there is anything I can help with.

**Comment by pvinis** [comment]
I saw the fix PR was closed. Is there a better way to fix this or something?

**Comment by jan-auer** [comment]
We will fix this by reverting the breaking change and improving usage docs around the matter. We haven’t had the time to fully assess this yet and will update the thread as soon as possible.

**Comment by pvinis** [comment]
Is there a workaround we can use for now, without running this on a mac?

**Comment by jan-auer** [comment]
The only workaround for now would be to specify both the bundle and version on the command line. 

After reverting, the proper usage will be to pass `<bundle>-<version>` to the `—bundle-id` option. We will point this out in the release notes.

**Comment by pvinis** [comment]
What if we didn't use versions at all before?

**Comment by jan-auer** [comment]
Sentry requires versions to function properly, I would be curious how this might have worked before. What did you pass as bundle identifier in your case? My understanding always was that appcenter also always requires a version number. 

The intention of that command line option was to specify a unique name for every new release, which includes a bundle name and said version. This was totally not clear from docs.

**Comment by pvinis** [comment]
This was our command before:

`SENTRY_PROPERTIES=./ios/sentry.properties ./node_modules/@sentry/cli/sentry-cli react-native appcenter Bla/BlaBla-ios ios ./output/js/ios --deployment Branch-123 --bundle-id com.ourcomp.app-Alpha`

**Comment by pvinis** [comment]
I think appcenter just autoincrements the version numbers, so it was working fine before.

**Comment by pvinis** [comment]
As extra info, we used `1.41.0` of cli, and with `1.46.0` the same command does not work anymore.

**Comment by jan-auer** [comment]
Yes, we regressed in 1.44.4 and will most likely roll back the behavior.

**Comment by ospfranco** [comment]
facing the same issue on 1.47, when can we expect the fix to land?

**Comment by pvinis** [comment]
Any news on this? We still have the old version because the new one is broken.

**Comment by ospfranco** [comment]
Hey, I just run into another issue, there is some regression break on the latest sentry-cli with codepush, the release name does not get matched properly, however with the latest version it started again, but that means this issue also started again.

Any news on this?

**Comment by ospfranco** [comment]
Well, I got this working by manually adding the version name into the script, everytime I update the app version I now have to update this (I could probably script my way around this, but I don't want to), the final command is as follows:

```export SENTRY_PROPERTIES=./ios/sentry.properties
npx sentry-cli react-native appcenter \
  --bundle-id $IOS_BUNDLE_ID \
  --version-name $APP_VERSION \
  --deployment $CODEPUSH_ENV \
  Capmo/mobileapp-ios-production ios ./build/CodePush```

**Comment by StarryFire** [comment]
1. Put this just below `Sentry.init` in your codebase
```
codePush.getUpdateMetadata().then((update) => {
      if (update) {
        Sentry.setDist(`codepush_${update.label}`);
      }
    });
```

2. To deploy changes via codepush, run the following command

```
appcenter codepush release-react --sourcemap-output --app APP_NAME --output-dir ./build -d DEPLOYMENT_NAME
```

3. To upload the sourcemaps of the deployed codebase to sentry, run the following commands

```
export SENTRY_PROPERTIES=./PLATFORM/sentry.properties
```

```
./node_modules/@sentry/cli/bin/sentry-cli react-native appcenter APP_NAME PLATFORM ./build/CodePush --deployment DEPLOYMENT_NAME --release-name RELEASE_NAME --dist DIST_NAME
```

where,
`APP_NAME` is `${owner_name}/${codepush_app_name}`.

`DEPLOYMENT_NAME` is the name of the deployment you want to deploy the changes under i.e. Staging/Production/etc. defined in your codepush app settings.

`PLATFORM` is the platform you want to deploy the changes for i.e. ios/android.

`RELEASE_NAME` for android is: `${applicationId}@${versionName}+${versionCode}` and for iOS is: `${bundleIdentifier}@${version}+${build}`.
This naming convention is mandatory for `RELEASE_NAME` because otherwise sentry's RELEASE Health feature won't work properly. For more details, look at https://github.com/getsentry/sentry-cli/issues/577#issuecomment-610272845
Also, because, when we build our release/staging app via XCode/Android Studio, Sentry always uses that release name (hardcoded by sentry) to upload our sourcemaps and so as not to make a new release on sentry for each codepushed version, we will put them all under one release name, divided by different distribution names i.e. `DIST_NAME`

`DIST_NAME` is `codepush_${codePushUpdateLabel}` where codePushUpdateLabel is the name of your codepush release eg. v21, v22, etc. You can check this out by going into your codepush app webpage on appcenter website and then `Distribute` -> `CodePush` -> `Select your respective deployment`
codePushUpdateLabel will be at the top of of the list since which is the update you just deployed on codepush. eg. `codepush_v22`

**Comment by bjackson** [comment]
I think the docs need to be updated:
https://docs.sentry.io/platforms/react-native/codepush/

**Comment by iuliuvisovan** [comment]
This is completely stupid. Can we get clear and non-ambiguous docs already? Do I really have to write a 30 line bash script just so that I can make Sentry work with CP?

**Comment by kyle-ssg** [comment]
Was lead to this issue after seeing builds fail in linux cicd builds, running ``npx sentry-cli react-native appcenter --help`` suggests that supplying --bundle-id should solve this. The hoops we have to go through in order to supply the mentioned arguments on [SO](https://stackoverflow.com/a/68177362/455225) make this so complicated.

**Comment by marandaneto** [comment]
@jennmueng Can you test out if the docs are up to date? https://docs.sentry.io/platforms/react-native/manual-setup/codepush/
The idea is that an RN App with CodePush and App center works as expected.

**Comment by jennmueng** [comment]
@marandaneto On macOS the [codepush release steps on the docs](https://docs.sentry.io/platforms/react-native/manual-setup/codepush/#making-releases) work as expected without issue, I don't have a non-macOS machine to test it with, would you be able to?

@kyle-ssg @iuliuvisovan 
I joined after this issue was opened and discussed, but to be clear your builds are failing due to the same issue as the original issue which is on non-macOS systems you need to manually specify the bundle id or release name right?

### The Problem

The whole gist of this problem comes from how we try to introduce convenience methods to simplify the release process that ended up getting broken.

You don't need to go through the difficult hoops mentioned in the [Stack Overflow reply](https://stackoverflow.com/a/68177362/9287775) because all-in-all the underlying issue is to just correctly match the release/dist string values assigned to the source maps for a version with the value that the SDK receives. If you know the version of the current release of your app and the codepush label of your app you can easily just upload the sourcemaps that are outputted by the codepush release-react command by passing `--release-name` and `--dist` to the sentry-cli:

```bash
sentry-cli react-native appcenter \
username/Some-App ios ./build \
--deployment "Staging" \
--release-name "com.example.app@1.0.0+codepush:v1" \
--dist "v1"
```

And you also don't even need to follow the release name convention of `com.example.app@1.0.0+codepush:v1` nor even use the codepush label for the dist. It was originally suggested as it allows for the most unique string that can be attributed to a version of an app. For example, if you version your apps with the general semver convention and increment the version number every time you make a release, for example `1.0.0`, you can just do

```js
Sentry.init({
  release: "1.0.0"
  dist: "1.0.0"
})
```

```bash
sentry-cli react-native appcenter \
username/Some-App ios ./build \
--deployment "Staging" \
--release-name "1.0.0" \
--dist "1.0.0"
```

and source maps will work just fine assuming version 1.0.0 is completely unique to this javascript bundle. And you do not do multiple codepush releases under the same version number.


_Also, we as of late are recommending against either calling `Sentry.init` inside `codePush.getUpdateMetadata` because initializing the SDK that late will cause it to miss out on fatal errors that can very well occur before the async return. We also recommend against using `setRelease` and `setDist` as errors from the native Android/iOS layer will not be attributed to the correct release and the release health/session tracking feature will also not work._

### Conclusion

We'll go back to the drawing board and see if we can design a new convenience release script or how we can change the current one to be more clear to use. And from what I see we need to document why we require the `release` and `dist` values and how they're not really that complicated.

**Comment by marandaneto** [comment]
@jennmueng thanks for the detailed investigation.

> @marandaneto On macOS the codepush release steps on the docs work as expected without issue, I don't have a non-macOS machine to test it with, would you be able to?

Just to confirm, have you tested codepush `and` appcenter, together, right?

**Comment by jennmueng** [comment]
@marandaneto Yes, both the codepush release command and appcenter sourcemap upload command.

**Comment by marandaneto** [comment]
For non-macOS devices: the command should rather be, e.g.:

`sentry-cli react-native appcenter {APP} ios ./build/CodePush --deployment {DEPLOYMENT} --dist {DIST} --bundle-id {BUNDLE_ID} --version-name {VERSION_NAME}`

Or, using `--release-name` instead which overwrites the whole release format.

`sentry-cli react-native appcenter {APP} ios ./build/CodePush --deployment {DEPLOYMENT} --dist {DIST} --release-name {RELEASE_NAME}`

For macOS, the release format is calculated automatically from the Xcode file, that's why you don't need to pass `--bundle-id` and `--version-name`.

If you're using macOS and still wanna overwrite the release format, `--release-name` is also an option.

`sentry-cli react-native appcenter {APP} ios ./build/CodePush --deployment {DEPLOYMENT} --dist {DIST} --release-name {RELEASE_NAME}`

**Comment by marandaneto** [comment]
[PR](https://github.com/getsentry/sentry-cli/pull/1113) for updating the log message which requires the version name too.

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. We will update the docs accordingly. I'd prefer someone to create a new issue with a fresh description if it'll still persist to be an issue.
Cheers!
