### ISSUE TITLE
Allow for organization scoped tokens

### ISSUE THREAD

**Issue by syabro** [getsentry/sentry-cli#581]
Developer can be fired and their account can be disabled.

**Comment by jan-auer** [comment]
You’re absolutely right! We’re working on organization scoped tokens already.

**Comment by syabro** [comment]
@jan-auer great! Any estimates?

**Comment by scefali** [comment]
@syabro Sorry for a lack of response the past few months. Organization tokens have since been released. You can manage org tokens using an internal integration. See the docs here: https://docs.sentry.io/workflow/integrations/integration-platform/#using-auth-tokens. If you have any further questions, please let me know (and please @ me so I get a notification :) ).
