### ISSUE TITLE
error: your platform and architecture (Linux-armv7l) is unsupported.

### ISSUE THREAD

**Issue by siredmar** [getsentry/sentry-cli#592]
I'm trying to run sentry-cli on ARM but receive the error
`error: your platform and architecture (Linux-armv7l) is unsupported.`

Do i have to build sentry-cli manually for ARM?
Is there a possibility to upload symbols directly via curl without using sentry-cli?

**Comment by adimajo** [comment]
I ran into the same error (Raspberry pi 3B+ on Buster Lite - trying to build RStudio Server).

**Comment by jan-auer** [comment]
We currently don't provide ARM builds for `sentry-cli`. Uploading symbols with `curl` is possible, although deprecated. Sentry CLI performs a lot of validation and processing steps during upload and I highly suggest to stick to sentry-cli.

Since this has come up more often, we can look into providing ARM builds.

In the meanwhile, is it possible to use sentry-cli on a separate host to upload symbols?

**Comment by adimajo** [comment]
Pardon my ignorance, I don't know `sentry-cli`, nor what you mean by symbols. It's just one of the many requirements before being able to build RStudio-server (since they don't provide builds for ARM either). So I guess I need to have `sentry-cli` installed. Can I do so by building from source as mentioned in the end of the README?

**Comment by andresrcs** [comment]
@adimajo you can build from source on raspbian with this commands 
```
# Install Rust and Cargo
sudo curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
# Install sentry-cli
sudo git clone https://github.com/getsentry/sentry-cli.git
sudo chown -R pi ~/sentry-cli
cd sentry-cli
cargo build
cd
sudo rm -rf sentry-cli
```
In case you need more guidance installing rstudio-server take a look to this guide
https://community.rstudio.com/t/setting-up-your-own-shiny-server-rstudio-server-on-a-raspberry-pi-3b/18982

**Comment by adimajo** [comment]
Thanks @andresrcs I came across your guide, among others, but were freightened by the amount of code needed. Now I read it thoroughly only to understand most part is related to shiny... Will try to make it work tonight, thanks.

**Comment by siredmar** [comment]
> Since this has come up more often, we can look into providing ARM builds.

Thanks! Can you specify any time when we can expect this?

**Comment by kamilogorek** [comment]
Created an issue for this https://github.com/getsentry/sentry-cli/issues/676

**Comment by gersakbogdan** [comment]
Until this will be available you can use my repo: https://github.com/gersakbogdan/sentry-cli-Linux-arm64
Those are built from source.

**Comment by paltman** [comment]
@gersakbogdan I try using yours by setting:

`SENTRYCLI_CDNURL: https://github.com/gersakbogdan/sentry-cli-Linux-arm64/raw/master`

in my `docker-compose.yml` file for the environment and the startup results in this (I run `npm I` at startup:

```
fetching sentry-cli-Linux-arm64 99%
fetching sentry-cli-Linux-arm64 100%
Error: spawn /app/node_modules/@sentry/cli/sentry-cli ENOENT
```

looking in `node_modules/@sentry/` I don't see a `cli` folder.

any ideas?
