### ISSUE TITLE
Electron 5.0.11 darwin: WARN Skipping debug file since it exceeds 2.00GB 

### ISSUE THREAD

**Issue by HyperSprite** [getsentry/sentry-cli#603]
I know this is discussed in closed issue #509 and I checked the change log to see if there have been any updates for this and didn't see any.

It seems [Electron 5.0.11](https://github.com/electron/electron/releases/tag/v5.0.11) symbols has exceeded the Sentry 2GB limit.
`  WARN    2019-10-04 14:19:12.243952 -07:00 Skipping debug file since it exceeds 2.00GB: Electron Framework.dSYM/Contents/Resources/DWARF/Electron Framework (2.01GB)`

Is there any solution or workaround for this?

Thanks

**Comment by jan-auer** [comment]
Yes, there's a workaround! You no longer need to upload Electron files at all and can instead activate the "Electron Symbol Server" in _Project Settings > Debug Files_:

![Electron Symbol Server](https://images.ctfassets.net/em6l9zw4tzag/5zQC3pIekvjL5tzVPgHKRI/8dfaab137a6c4ae860379c845987d6be/debug-information.png)

This server has symbols for all Electron versions, so the only thing you need to upload from now on are your own source maps or native extensions.

**Comment by HyperSprite** [comment]
Awesome, thanks for the info.

**Comment by Shafayet-LMI** [comment]
hi we are using a custom build of electron and so l believe pointing to the Built-in repos will not work for us. Has there been any improvements since? .... that will allow us to upload a custom Electron Framework.dym file (>2.00 GB)?

**Comment by Shafayet-LMI** [comment]
@jan-auer ?

**Comment by jan-auer** [comment]
There are two workarounds you can employ:

- If you're on a business plan at Sentry, you can place the files on another storage and Sentry downloads it from there. This storage can be an Amazon S3 or Google Cloud Storage, as well as a custom HTTP server that serves the files. You can find more information about this here: https://docs.sentry.io/platforms/native/data-management/debug-files/#custom-repositories

- If this is not an option, then you can convert the files to `.sym`, like GitHub does for their Electron distribution. Those files are usually an order of magnitude smaller. To convert, you will need a tool called `dump_syms` from Google. You can find an unofficial build of this tool that we use for testing here: https://github.com/getsentry/breakpad-tools#readme. Note that you need to run the tool on the respective platform that you're converting symbols for (e.g. PDBs on Windows, dSYMs on Mac), otherwise it won't work.

By converting to `.sym` you lose inline information and some accuracy in stack traces, but it has no additional infrastructure and plan requirements for you.

**Comment by Shafayet-LMI** [comment]
> 
> 
> There are two workarounds you can employ:
> 
>     * If you're on a business plan at Sentry, you can place the files on another storage and Sentry downloads it from there. This storage can be an Amazon S3 or Google Cloud Storage, as well as a custom HTTP server that serves the files. You can find more information about this here: https://docs.sentry.io/platforms/native/data-management/debug-files/#custom-repositories
> 
>     * If this is not an option, then you can convert the files to `.sym`, like GitHub does for their Electron distribution. Those files are usually an order of magnitude smaller. To convert, you will need a tool called `dump_syms` from Google. You can find an unofficial build of this tool that we use for testing here: https://github.com/getsentry/breakpad-tools#readme. Note that you need to run the tool on the respective platform that you're converting symbols for (e.g. PDBs on Windows, dSYMs on Mac), otherwise it won't work.
> 
> 
> By converting to `.sym` you lose inline information and some accuracy in stack traces, but it has no additional infrastructure and plan requirements for you.

hi @jan-auer  thanks a lot!! I think both of these are excellent options that will get us moving forward! Really appreaciate the prompt response :)
