### ISSUE TITLE
[1.52.0] mkdirp 1.0.0 only support node >= 10

### ISSUE THREAD

**Issue by kkdev163** [getsentry/sentry-cli#695]
sentry-cli update the version mkdirp to '^1.0.0' in the release of 1.52.0, which is only supporting node >=10. [issue](https://github.com/isaacs/node-mkdirp/issues/10)

this causes some people can't install in the lower version node.

**Comment by kamilogorek** [comment]
`mkdirp 1.0.0` patched a vulnerability issue described here https://github.com/getsentry/sentry-cli/pull/685 and it's no longer supported by the author: 

> Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

See: https://www.npmjs.com/package/mkdirp/v/0.5.4

If you still want to use old version, you can use `yarn` and force the old`mkdirp` version `0.5.4` using selective version resolution - https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by LinusU** [comment]
Sentry-cli currently declares that it supports Node.js 8.x though:

https://github.com/getsentry/sentry-cli/blob/6d9ba9f3e3f061839735e986839d8935672e6121/package.json#L52-L54

I think that a better approach would be to downgrade the dependency to `^0.5.4` for the 1.x release line, since upgrading to 1.x is a breaking change (since it drops support for Node.js 8)

**Comment by kamilogorek** [comment]
Fair enough. Patched here https://github.com/getsentry/sentry-cli/pull/699 and created a separate issue to keep track of it.

**Comment by aaharu** [comment]
How about using [make-dir](https://www.npmjs.com/package/make-dir)

**Comment by kamilogorek** [comment]
@aaharu starting node 10, we can just use `mkdirSync('', { recursive: true });`
