### ISSUE TITLE
centry-cdn.com uses the IP that is blocked in Russia

### ISSUE THREAD

**Issue by ilyadoroshin** [getsentry/sentry-cli#748]
Hi, guys! 

We're experiencing issues downloading sentry cli (and the whole thing breaks) on postinstall due to the fact that cdn is being used on blocked IP in Russia 
```
FetchError: request to https://downloads.sentry-cdn.com/sentry-cli/1.49.0/sentry-cli-Linux-x86_64 failed, reason: connect ECONNREFUSED 151.101.66.217:443
```
https://reestr.rublacklist.net/search/?q=151.101.130.217

**Comment by tonyo** [comment]
Not much we can do here, unfortunately, since the CDN we use (and the respective IP addresses) is managed by Fastly.

You can try to download the binaries directly from GitHub releases: https://github.com/getsentry/sentry-cli/releases/tag/1.53.0, or use `SENTRYCLI_CDNURL` variable if you install with `npm` or `yarn`:
```
SENTRYCLI_CDNURL=https://github.com/getsentry/sentry-cli/releases/download/ npm install @sentry/cli
```
