### ISSUE TITLE
Add `silent` flag to `releases files upload-sourcemaps` to prevent `Source Map Upload Report` log

### ISSUE THREAD

**Issue by konclave** [getsentry/sentry-cli#765]
We have large amount of source files in our project so that can reduce significantly the size of log in CI build. 
`sentry-webpack-plugin` already has this option. It would be nice if sentry-cli supported it too.

**Comment by drjayvee** [comment]
I fully expected `--log-level=warn` to silence this report.

The output is written to `stdout`, so it's also not possible (/ easy) to redirect to `/dev/null`.

**Comment by kamilogorek** [comment]
> The output is written to stdout, so it's also not possible (/ easy) to redirect to /dev/null.

You mean redirect "specific" output or any sentry-cli output?

**Comment by drjayvee** [comment]
If the summary were output to `stdout` and the long report to `stderr`, then one could `sentry-cli ... 2> /dev/null`.

**Comment by kamilogorek** [comment]
The tricky part is that `log-level=warn` is the default, and making this report `info` level would effectively silence it for anyone expecting it currently by default. On the other hand, changing default to `info` would enable multiple other outputs which are currently not logged by default.

**Comment by drjayvee** [comment]
I see the problem. I really feel that the report belongs in `info`, and certainly not `warn`.

I've only started using Sentry a few days ago, so I don't feel confident in making a recommendation as to what to do.

I think I'll change the `log-level` to `error` in our CI.

**Comment by kamilogorek** [comment]
Unfortunately this report is not produced through the logger, which is something I'd want to change. However, then, this levels discrepancy issue becomes real. WDYT @jan-auer ?

**Comment by jan-auer** [comment]
If we look at it like this, the report is not really part of logging. It's similar to `upload-dif`, where parts of the output are printed directly to stdout instead of through the logger.

We already have a `--quiet` option on a few commands including `info` and `releases info`. I'd suggest implementing another one like this. In a follow-up, you can lift it into a global argument and redirect all output through a central utility that honors the flag.

**Comment by kamilogorek** [comment]
`2.0.0-beta.0` has been released, give it a try and let me know if your issue has been resolved 🎉

**Comment by jenskuhrjorgensen** [comment]
@kamilogorek I just tried the newest version of @sentry-cli (v2.11.0) and the output is still extremely verbose with more that 15.000 lines outputted for `sentry-cli releases ...`

![Screenshot 2023-01-09 at 14 58 33](https://user-images.githubusercontent.com/28528363/211325015-afdc7ee8-8c9b-4451-baf5-0511a8e58eab.png)

Is this expected/is there a way to silence this?

**Comment by kamilogorek** [comment]
@jenskuhrjorgensen `--silent` will disable source map upload report.

**Comment by jenskuhrjorgensen** [comment]
@kamilogorek that worked perfectly - thanks! However, now that I have the solution, I can still not find any documentation on the `--silent` flag on https://docs.sentry.io/product/cli/ - am I looking in the wrong place?

**Comment by kamilogorek** [comment]
No, you are totally right, it's not there. Only `sentry-cli --help` for that command would tell you this. Would appreciate PR :)

**Comment by drjayvee** [comment]
The CLI (version `2.11.0`) doesn't even list `upload-sourcemaps` as a subcommand:
```
$ sentry-cli help releases files
sentry-cli-releases-files
Manage release artifacts.

USAGE:
    sentry-cli releases files [OPTIONS] <VERSION> <SUBCOMMAND>

# ARGS and OPTIONS omitted for brevity

SUBCOMMANDS:
    delete    Delete a release file.
    help      Print this message or the help of the given subcommand(s)
    list      List all release files.
    upload    Upload files for a release.
```

Next, `--silent` is just an alias for `--quiet`?
```
$ sentry-cli help releases files upload-sourcemaps |grep -B2 silent
        --quiet
            Do not print any output while preserving correct exit code. This flag is currently
            implemented only for selected subcommands. [aliases: silent]
```

Very confusing.

**Comment by kamilogorek** [comment]
> The CLI (version 2.11.0) doesn't even list upload-sourcemaps as a subcommand:

Because there's no such command in v2. It's `sentry-cli sourcemaps upload` - https://github.com/getsentry/sentry-cli/releases/tag/2.0.0 (its there "technically", as hidden, to preserve backward-compat for some users).
Our cli docs definitely need a refresh, but also all the commands listed there should work just fine. 

Created a ticket for that, thanks for pointing that out - https://github.com/getsentry/sentry-cli/issues/1429

> Next, --silent is just an alias for --quiet?

Source map upload logging is not silenceable in v1, that was a feature added to the v2 - https://github.com/getsentry/sentry-cli/blob/401b91dfa6a6a3f034d3ae690d01d73505b972a0/src/utils/sourcemaps.rs#L253-L256

**Comment by valerii15298** [comment]
The same issue is with vite plugin. *Source Map Upload Report* prints random ids, takes 99% of all logs so it is impossible to see what is really important. Would be nice to have an option to disable only that. I can put `silent: true` but I do not wanna disable all logs. It is related to this issue but I can create new one...
