### ISSUE TITLE
error: Couldn’t not find the SHA of the previous release in the git history.

### ISSUE THREAD

**Issue by sgametrio** [getsentry/sentry-cli#792]
Hey everybody,
I'm using Sentry on a repository where we have several branches that upload source maps to Sentry, each time with a new release. 

When calling these CLI commands:
```
sentry-cli releases new ${CI_COMMIT_SHA}
sentry-cli releases set-commits --auto ${CI_COMMIT_SHA}  # <--- here I get the error
```

It happens that sometimes we get the error
```
error: Couldn’t not find the SHA of the previous release in the git history. Increase your git clone depth.
```
And if I increase the git depth, it shows`error: No commits found. Leaving release alone.`

It has to be said that when merging into master we are squashing commits and that could be the cause of our problems, but we can't figure out exactly because sometimes the set-commits command just work as expected.

**Comment by kamilogorek** [comment]
`--auto` is a flag, and it doesn't accept any additional value, so this last `${CI_COMMIT_SHA}` is ignored.

If you squash or rebase git history, then as you already mentioned there's a chance that hashes will be overridden, and we won't be able to find old release reference. If you cannot change that, then you'll most likely have to explicitly tell the CLI which hash is the one that you want to use as the base, eg.

`sentry-cli releases set-commits "$VERSION" --commit "my-repo@from..to"`

**Comment by vinnymac** [comment]
@kamilogorek your advice is certainly helpful, but the first thing you mention is that `--auto` takes no additional value and that `${CI_COMMIT_SHA}` is ignored. The [documentation](https://docs.sentry.io/product/releases/#associate-commits-with-a-release) for the CLI has examples that show this exact usage however.

<img width="771" alt="Screen Shot 2020-09-12 at 12 00 23 PM" src="https://user-images.githubusercontent.com/1832781/92999535-8b522900-f4ef-11ea-9cb4-eb80e5a37dfa.png">


Is the example wrong, or does the auto flag actually accept a value?

I see competing [examples here](https://docs.sentry.io/cli/releases/#sentry-cli-commit-integration).

<img width="769" alt="Screen Shot 2020-09-12 at 12 01 41 PM" src="https://user-images.githubusercontent.com/1832781/92999551-ba689a80-f4ef-11ea-8795-dc54f178586c.png">

**Comment by kamilogorek** [comment]
@vinnymac good catch, updated my comment. I misread the command 😅

**Comment by x-yuri** [comment]
@kamilogorek @sgametrio Actually I believe `sentry-cli` shouldn't fail because of a rebase. Just store in a release a list of associated commits (unless you already do), and look in the git history not for a release name, but for every commit in turn. Unless you find the commit in the previous release, check the one before that. Maybe 2 releases is generally enough. But you can add a switch to specify "how much is too much." You want releases to not branch? Add a `--force` switch. Or at least document the way to use `sentry-cli` that doesn't choke on rebases:

```sh
VERSION=$(sentry_cli releases propose-version)
sentry_cli releases new -p "$sentry_prj" "$VERSION"
sentry_cli releases set-commits --auto "$VERSION" || {
    PRV_VERSION=`curl -sS \
        -H "Authorization: Bearer $SENTRY_AUTH_TOKEN" \
        "$sentry_base_url/organizations/$sentry_org/releases/$VERSION/previous-with-commits/" \
        | jq -r .version`
    sentry_cli releases delete "$PRV_VERSION"
    sentry_cli releases set-commits --auto "$VERSION"
}
```

We can discuss the issue if you feel like it.

> If you cannot change that, then you'll most likely have to explicitly tell the CLI which hash is the one that you want to use as the base, eg.

This seems reasonable, but in practice is useless, unless you do it by hand in your local repository. Sorry for being blunt. Where will I find the now non-existent commits on a CI server to determine the base commit? In the reflog?

And actually I have a number of questions for which I don't expect to receive answers. Except for possibly here? Anyways, I'm open for suggestions. The first one is that I'm reluctant to install the GitHub application. Judging from the [wording][1] it seems like once I do, I can never go back. Then you suggest using [cli over api][2]. Why is that? You say that releases are global per organization. Is using commit hashes safe? The documentation makes one think one should do something different if one doesn't want to install the GitHub application. But from I can see, the difference only in the result (more info on Sentry probably).

[1]: https://forum.sentry.io/t/is-there-no-way-to-deassociate-a-github-account-from-sentry-organization/11100
[2]: https://docs.sentry.io/product/releases/#associate-commits-with-a-release
[3]: https://docs.sentry.io/cli/releases/

**Comment by JustDoItSascha** [comment]
Is there any progress here? The set-commits command is failing here, but we haven't done a squash or a rebase. Is there any possibility to get around this problem? Because right now the only way to exit this loop hole is to completely disable set-commits command, right? Or is it possible to say "use auto, but if you don't find something, just take the last commit in history"?

**Comment by karatekaneen** [comment]
I ran in to this issue on our CI system. It boiled down to that it only fetched a shallow copy of the git repo.
I solved it by running `git fetch --unshallow` before the `sentry_cli releases set-commits --auto "$VERSION"`.

Hope this can help someone.

**Comment by klarkc** [comment]
@karatekaneen did you found a way to fetch without unshallowing? This make a bottleneck in our CI. Would be nice if we shallow  fetch only needed commits of sentry-cli

**Comment by castorinop** [comment]
I have this error with a squash merge

**Comment by Rennzie** [comment]
I had a the same issue. Turns out my github integration wasn't liked to the repo. I needed to allow access to the repo in my Github orgs app settings. Then link it in the Sentry org integration for Github config.

**Comment by kamilogorek** [comment]
Thanks for the info @Rennzie

**Comment by josh-** [comment]
> I ran in to this issue on our CI system. It boiled down to that it only fetched a shallow copy of the git repo. I solved it by running `git fetch --unshallow` before the `sentry_cli releases set-commits --auto "$VERSION"`.
> 
> Hope this can help someone.

Just ran into this on GitHub Actions - if anyone is also seeing this error in your workflow when using `actions/checkout`, it's because this action does a shallow clone by default and can be configured to fetch all or a specified number commits with [`fetch-depth`](https://github.com/actions/checkout#usage). For example:

```yml
- uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

**Comment by LeonardoRosaa** [comment]
When running the command `flutter packages pub run sentry_dart_plugin` with the `actions/checkout` configured as shown below:

```yaml
- uses: actions/checkout@v4
  with:
    fetch-depth: 0
```

I encounter the following issue:

```shell
Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from the local git tree.

error: Could not find the SHA of the previous release in the git history. If you limit the clone depth, try to increase it. Otherwise, it means that the commit we are looking for was amended or squashed and cannot be retrieved. Use --ignore-missing flag to skip it and create a new release with the default commits count.
```
