### ISSUE TITLE
Installing sentry-cli on bash in windows fails

### ISSUE THREAD

**Issue by ajbeaven** [getsentry/sentry-cli#800]
When I run the following script in bash:
```
curl -sL https://sentry.io/get-cli/ | bash
```

I receive the following error:
> SENTRY_DOWNLOAD_MINGW64_NT-10.0_x86_64: bad substitution

I assume it's because the version above doesn't exist in the https://sentry.io/get-cli/ script that is executed?

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/getsentry/pull/4318
Should be merged and deployed soon.

**Comment by kamilogorek** [comment]
@ajbeaven fixed. You should be able to use the command now. Cheers!

**Comment by hatton** [comment]
Still fails, because it calls `sudo`:

> $ curl -sL https://sentry.io/get-cli/ | bash
This script will automatically install sentry-cli 1.58.0 for you.
Installation path: /usr/local/bin/sentry-cli
############################################################################################################ 100.0% 
bash: line 60: sudo: command not found
