### ISSUE TITLE
Docker multi-arch build

### ISSUE THREAD

**Issue by JanMikes** [getsentry/sentry-cli#908]
Hello!

Currently when running official Docker image on arm it will result into error:
```
➜  docker run --rm -v $(pwd):/work getsentry/sentry-cli --help
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

It is because images are built only for amd64: https://hub.docker.com/r/getsentry/sentry-cli/tags?page=1&ordering=last_updated

In order to buid multi-arch images, i think this script has to be changed: https://github.com/getsentry/sentry-cli/blob/master/scripts/build-in-docker.sh

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since with https://github.com/getsentry/sentry-cli/pull/890 PR.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
